### ISSUE TITLE
Bug, when click on btn - form run submit 

### ISSUE THREAD

**Issue by ntvsx193** [angular-ui/ui-select#552] opened 2014-12-27 23:24 UTC
I use whis module in form html element.
When btn select clicked - form submitted.

It's quick fix: set button type="button"

**Comment by havenchyk** [comment] 2015-01-10 12:43
Hello, @amcdnl, is there a reason, why PR for this issue isn't merged yet?

**Comment by brianfeister** [comment] 2015-01-12 20:55
Duplicate of #503.

**Closed by brianfeister** 2015-01-12 20:55 UTC
