### ISSUE TITLE
ui-select search-enabled does not evaluate the condition specified whenever there is a change of value

### ISSUE THREAD

**Issue by sarathkumar6** [angular-ui/ui-select#1698] opened 2016-07-05 15:06 UTC
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:

UI-Select:

Bootstrap/Select2/Selectize CSS (if applicable):

code:
search-enabled="companies.available.length > 6"

Description: 
The requirement is that the search box should only appear if there are more than 6 names in the drop down. I have two different modes (admin and employee) when I switch between modes the condition specified in the search-enabled attribute is not evaluated until I refresh the page after switching to either admin or employee

theme="select2"
ng-change=".selectCompany()"
class="company-select white"
ng-if="scsc.companies.available.length > 1"
search-enabled="scsc.companies.available.length > 6"
reset-search-input="'false'">

**Comment by sarathkumar6** [comment] 2016-07-05 15:09
code:
search-enabled="companies.available.length > 6"

Description: 
The requirement is that the search box should only appear if there are more than 6 names in the drop down. I have two different modes (admin and employee) when I switch between modes the condition specified in the search-enabled attribute is not evaluated until I refresh the page after switching to either admin or employee

<ui-select ng-model="companies.selected"
               theme="select2"
               ng-change=".selectCompany()"
               class="company-select white"
               ng-if="scsc.companies.available.length > 1"
               search-enabled="scsc.companies.available.length > 6"
               reset-search-input="'false'">

**Comment by user378230** [comment] 2016-07-05 15:36
Did you try `search-enabled="{{scsc.companies.available.length > 6}}"`?

**Comment by sarathkumar6** [comment] 2016-07-05 15:45
user378230 I tried it throws me CEU dialog error

**Comment by BrianLenzo** [comment] 2016-07-07 13:50
This issue is a duplicate of https://github.com/angular-ui/ui-select/issues/505

This is a demonstration of the problem: http://plnkr.co/edit/5MloUIxH1kQma6vfvHBB?p=preview

I tested it with all ui-select from 18.0 back to 12.1.  It is present in all versions.

**Comment by user378230** [comment] 2016-07-07 16:01
Closed by #1707 via #505, thanks @BrianLenzo!

**Closed by user378230** 2016-07-07 16:01 UTC
