### ISSUE TITLE
search input always under selected items

### ISSUE THREAD

**Issue by JeffGreat** [angular-ui/ui-select#696] opened 2015-02-24 10:58 UTC
Just for information:

The input field is always under the selected items on my uiselect multiple. since I don't have enought time to invistigate I'm not able to say why I get this special behavior. My site has several js files and css so it can be the reason why. 
What I can say is that the search input width has always the width of its parent. that's why it comes under the selected items.

Anyway the work around I found is to set the $timeout at 100ms in the sizeSearchInput function. In this way the DOM has enought time to update and the function can calculate the right width.

Note: I can make it work with 0ms while debugging in Chrome.

**Comment by sergonius** [comment] 2016-03-11 12:23
Funny, I have exactly the same issue, can't really get to the bottom of this...

**Comment by wesleycho** [comment] 2016-03-27 20:38
Closing this due to lack of Plunker - feel free to open a new issue with reproduction in Plunker based off of the latest release.

**Closed by wesleycho** 2016-03-27 20:38 UTC
