### ISSUE TITLE
Bower version update?

### ISSUE THREAD

**Issue by btmdave** [angular-ui/ui-select#779] opened 2015-03-19 16:53 UTC
Seems like the version in bower has no dist folder, any plans to include this?

**Comment by btmdave** [comment] 2015-03-19 16:56
Also it seems to be completely different code base for `ui-select`? Has src/select3, no gulp files, uses grunt...

**Comment by btmdave** [comment] 2015-03-19 16:57
`ui-select` is pulling `angular-ui-select3` from bower...

**Comment by bbrown** [comment] 2015-03-19 17:00
Are you running ```bower install angular-ui-select``` as indicated in the [docs](https://github.com/angular-ui/ui-select/wiki/Getting-Started)? I initially ran ```bower install ui-select``` and that's the situation I ran into.

**Comment by btmdave** [comment] 2015-03-19 18:58
Yeah i ended up getting it with `angular-ui-select`.  The package name in bower is `ui-select` - guess that should be updated?

**Comment by wesleycho** [comment] 2016-03-27 20:55
Closing as a duplicate of another issue

**Closed by wesleycho** 2016-03-27 20:55 UTC
