### ISSUE TITLE
BUG - Repeated ui-select with filter function on choices "kill" selected item

### ISSUE THREAD

**Issue by betonetotbo** [angular-ui/ui-select#1706] opened 2016-07-07 14:28 UTC
Example and extra details on:
http://codepen.io/betonetotbo/pen/QErOmv

**Comment by user378230** [comment] 2016-07-07 14:44
Duplicate of #1672 ?

**Comment by betonetotbo** [comment] 2016-07-08 20:55
Yes, can be dupplicated.

I tested using `remove-selected=true` attribute as a workarround.

**Closed** 2016-07-08 23:19 UTC
