### ISSUE TITLE
tagging-tokens does not support key-modifieres

### ISSUE THREAD

**Issue by jonashartwig** [angular-ui/ui-select#887] opened 2015-04-27 08:58 UTC
Hi,

In version 0.11.2 if we would use ; for tagging-tokens it would split, but not replace in the input string corectly due to the keydown keycode beeing , not ;.

possible solutions: change to keypressed event and replace MAP

**Comment by user378230** [comment] 2016-03-15 21:22
Closing as dupe of #815

**Closed by user378230** 2016-03-15 21:22 UTC
