### ISSUE TITLE
Only a object property can be bound to model

### ISSUE THREAD

**Issue by budhajeewa** [angular-ui/ui-select#1120] opened 2015-08-03 08:46 UTC
The following works:

HTML:

```
<ui-select
		data-ng-model="foo.month"
		data-ng-change="change()"
		>
...
</ui-select>
```

JS:

```
$scope.foo = {month:null};

$scope.change = function () {
	console.log($scope.foo.month); //"buz", the expected output.
};
```

But following doesn't:

HTML:

```
<ui-select
		data-ng-model="bar"
		data-ng-change="change()"
		>
...
</ui-select>
```

JS:

```
$scope.bar = null;

$scope.change = function () {
	console.log($scope.bar); //undefined
};
```

Why only object properties can be bound to model? This is not consistent with native Angular behaviour.

**Comment by budhajeewa** [comment] 2015-08-03 08:54
Following StackOverflow question address this issue as well: http://stackoverflow.com/questions/25937098/ng-model-is-not-getting-changed-in-ui-select

**Comment by randikagit** [comment] 2015-08-03 08:54
I can confirm this.When assigned a scope variable to the ui-select model it gives undefined.

**Comment by Nadrendion** [comment] 2015-08-06 15:20
Isn't that the common Angularjs-way?
If you try to assign a value to a variable in a scope that doesn't have that variable, the variable will be created on the current scope. This is happening even if the variable is present in any parent scope.

But if a parent variable is declared as an object and the object contains a variable that you try to assign a new value to in a childscope, then the parent object will be changed.

**Comment by budhajeewa** [comment] 2015-08-07 01:00
@Nadrendion I don't think it's the "common Angularjs-way".

As explained above, the variable is defined in the `$scope` beforehand. The only difference is that it works when the variable is a object (`$scope.bar = {month:null}`), and it doesn't work when the variable is just null (`$scope.bar = null`).

I don't think this is "common Angularjs-way" because both works when we use plain ol' `<select>`.

**Comment by Nadrendion** [comment] 2015-08-07 05:11
@budhajeewa A <select> is usually in the same scope as the scope variable, but here you have a child scope.  

Let's say you have this layout:
<div ng-controller="parentCtrl">
{{bar}}
     <div ng-controller="childCtrl">
           {{bar}}
     </div>
</div>

Both printouts will print the same value, but if you run some function in the childCtrl that assigns a new value to bar then only the inner bar will change.

**Comment by budhajeewa** [comment] 2015-08-07 13:18
@Nadrendion : What does that have to do with the issue I explained above?

See https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks on how to use code blocks in GitHub Flavored Markdown.

**Comment by Nadrendion** [comment] 2015-08-07 14:11
The ui-select has its own scope. 
So for reading a parent variable that you send in, that isn't declared as a variable of an object, it works just fine, but when the ui-select controller is modifying the variable, it will only create a new variable with that name on its own isolated scope.

That is why you need to refer to the variable in an object from your own scope when sending it to the ui-select for modification.

**Comment by budhajeewa** [comment] 2015-08-07 14:15
Nope, that doesn't explain why `$scope.foo.bar` works but `$scope.foo` doesn't when assigned to as the `ui-select`'s model.

**Comment by Nadrendion** [comment] 2015-08-07 14:32
@budhajeewa I would like to know why it doesn't explain it, but that is probably something that should be explained outside of this context.

**Comment by budhajeewa** [comment] 2015-08-07 14:40
@Nadrendion : Both `foo.month` and `bar` are variables in the same scope. Why would `ui-select` be able to bind to one but not other? The only difference is that `foo.month` is an object property and `bar` a plain ol' variable.

`select` works with either. So, the issue is with `ui-select`.

**Comment by Nadrendion** [comment] 2015-08-07 14:46
It is not the scope itself that is the issue, but the variable location. 
No matter if you have your own parent and child-scopes or uses the isolated scope of the ui-select as a childscope it will work the same as soon as you involve a childscope and try to modify a parent scope variable. 

No new scope is introduced when using a regular `<select>`so that is why there is no issue with that.

**Comment by budhajeewa** [comment] 2015-08-07 14:54
This is all I know:

 - I can bind `ui-select`'s model to a `foo.month`, given that `$scope.foo = { month: null };`.
 - I can not bind `ui-select`'s model to `bar`, given that `$scope.bar = null`.

All I see is `ui-select` being able to bind to a object property but not to a variable, both in same scope.

**Comment by Nadrendion** [comment] 2015-08-07 15:09
yes, and all I know is that the behavior you are experiencing is working as intended.
I think we will have to agree to disagree on this matter.

**Comment by budhajeewa** [comment] 2015-08-07 15:14
I think `ui-select` should adopt the method how the plain `select` works.

**Comment by RodolpheGohard** [comment] 2015-08-18 15:44
I'm not sure I fully understand the object of the debate, but this is clearly a bug that needs fixing, binding ng-model to the inside scope doesn't make any sense.

**Comment by budhajeewa** [comment] 2015-08-19 06:14
@RodolpheGohard : You can safely ignore the debate, which I think was not necessary.

**Comment by user378230** [comment] 2016-03-15 22:21
Closing, as ng-model requires a **dot** as per http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model and the ui-select wiki.

**Closed by user378230** 2016-03-15 22:21 UTC
