### ISSUE TITLE
v0.16.1 bower.json still shows version as v0.14.1

### ISSUE THREAD

**Issue by fmalk** [angular-ui/ui-select#1568] opened 2016-04-20 23:15 UTC
Installing via bower right now sucessfully downloads v0.16.1, but its `bower.json` is outdated and incorrectly lists itself as v0.14.1 (but `package.json` is correct)

**Comment by user378230** [comment] 2016-04-21 11:23
Hi! Please use search function before raising issues. Thanks! :smile: 

Closing as duplicate of #1521.

**Closed by user378230** 2016-04-21 11:23 UTC
Labels: duplicate
