### ISSUE TITLE
Template Cache issue

### ISSUE THREAD

**Issue by pratikvasani** [angular-ui/ui-select#992] opened 2015-06-04 14:51 UTC
Hi 

I am using UI Select with ngRoute Module , 

As a part of the my code I need to clear the ngRoute template cache.

 I run the following command $templateCache.removeAll();

After running this command when I go to a controller which uses UI select , it fails with a 
Failed to load template: bootstrap/select-multiple.tpl.html error,

I would expect the control to re load the template in case it cant find it in the cache ? Is there a way i can achieve this ? is this a bug ?

**Comment by micha149** [comment] 2015-06-22 06:52
I think you're using the compiled version of ui-select. In this package the template cache will be prefilled with the templates, which ui-select needs. If you clear the cache, the templates will be removed, too.

To solve your problem you can add the necessary template files to your public folder or fill them into the cache again, after it was cleared. Have a look at: https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L1804-L1816

**Comment by pnvpratik** [comment] 2015-06-24 14:31
@micha149 i saw the js code in the select.js file , it loads the template string at the end, should i be using the version from  the source folder in case I am playing around with the cache ? It would mean I also have to include all the template html files in my project instead of just the one JS file I have now.

**Comment by micha149** [comment] 2015-06-24 17:43
This is a good question. You can just copy these lines fro the select.js file, but you have to remember to update them when you update the dependency. Cleaner, but with more code, could be a solution which generates these lines from the current src folder.

**Comment by awerlang** [comment] 2015-08-07 03:12
I suggest you to only remove templates that you own yourself. Take a look how I do it: https://github.com/awerlang/angular-wt-apps/blob/master/src/development.js?ts=2

**Comment by hoetmaaiers** [comment] 2015-09-01 07:41
I do not run any `templateCache.removeAll()` or something alike, yet still the templates are trying to be fetched remotely: `http://localhost:3000/select2/match-multiple.tpl.html`. Because of a Gulp & Webpack buildchain, I don't want to remotely load the templates but require them and manually inject them into the templateCache (if they are missing...).

I wonder why the template files are not automatically injected as above described.

**Comment by micha149** [comment] 2015-09-01 09:00
Are you using `dist/select.js`?

**Comment by hoetmaaiers** [comment] 2015-09-01 09:06
Yes I am using `/dist/select.min.js`

**Comment by hoetmaaiers** [comment] 2015-09-07 09:39
When I `console.log($templateCache.get("select2/match-multiple.tpl.html"));`, the template is already present in the templateCache, yet still a http request is done to fetch the template. 

Is this some setting/behaviour I can disable?

**Comment by hitchcockwill** [comment] 2016-02-22 15:45
I'm running into this same issue. Anyone come up with a fix for this?

**Comment by user378230** [comment] 2016-02-22 16:49
The templates are added to cache similar to any other angular template. See: https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L2031

There must be an issue elsewhere in your application which is causing a problem saving to the `$templateCache` can you provide a reproduction plunkr?

**Comment by wesleycho** [comment] 2016-03-27 22:45
Closing this as a usage issue.

**Closed by wesleycho** 2016-03-27 22:45 UTC
