### ISSUE TITLE
The new 0.14 version performance is even worse than before

### ISSUE THREAD

**Issue by Avien** [angular-ui/ui-select#1404] opened 2016-01-26 09:25 UTC
Can someone address the performance issues?
I cant use this library

**Comment by user378230** [comment] 2016-01-27 16:36
Duplicate of #389 ?

**Comment by Avien** [comment] 2016-01-28 07:52
Yep,
Also same as https://github.com/angular-ui/ui-select/issues/1361
Very slow when opening,searching & removing, especially when there are multiple drop downs

I forked the project and did the changes I needed:
https://github.com/Avien/ui-select/tree/v0.13.4

**Comment by Narretz** [comment] 2016-01-29 08:14
@Avien dou should open a PR with your changes

**Comment by Avien** [comment] 2016-01-31 08:59
My changes are specific to my needs, I doubt it would fit others
Its also a fork from 0.13.2 and not from the latest version

**Comment by SargoDarya** [comment] 2016-02-01 09:05
Also with 183 Pull Requests open I don't think this will land anytime though.

**Comment by Narretz** [comment] 2016-02-12 10:06
The maintainers need to set priorities. For example, looking at the state of the issue queue, there should be a stop on features for the time being. Performance and compatibility fixes should be prioritized.

**Comment by buremba** [comment] 2016-02-18 22:26
@Narretz +1. Currently, this component is the only stable select component for Angular but the performance issues prevent us to use it in our production environment.

**Comment by Avien** [comment] 2016-02-25 08:28
So just upgraded to angular 1.5 and therefore needed to upgrade ui-select (0.14.3) to fix the transclude issue but the performance is awful!!
I cant search a multi select with 100 items , it is so slow, and also closing the menu is very slow
Unfortunately going back to my fork, and revert back to angular 1.4.x
Will have to find an alternative to ui-select

**Comment by Avien** [comment] 2016-02-25 09:46
I have managed to create a fix on the latest version which omits the newly animation added to the menu, apparently it slows down the rendering significantly.
Also added the ability to know when the component is filtered by emitting a 'uis:filter' event
https://github.com/angular-ui/ui-select/pull/1460

**Comment by jaxspades** [comment] 2016-03-07 20:38
Yeah, can we get this put in place please?

**Comment by user378230** [comment] 2016-07-11 18:18
Closing in favour of #389 & #648

**Closed by user378230** 2016-07-11 18:18 UTC
Labels: performance
