### ISSUE TITLE
Attempting gulp build fails with TypeError

### ISSUE THREAD

**Issue by andrewmurray** [angular-ui/ui-select#1861] opened 2016-12-02 16:15 UTC
Here is the output from my shell after doing a clone locally and npm install && bower install:

$ gulp
D:\Git\ui-select\node_modules\karma\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                                    ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (D:\Git\ui-select\node_modules\karma\node_modules\socket.io\lib\store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Git\ui-select\node_modules\karma\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:573:32)`

I'm running windows 10, node v7.1.0

Is a specific version of node required?

**Comment by rahmanfasalu** [comment] 2016-12-02 18:30
am also getting the same error,

**Comment by unelige** [comment] 2017-01-13 23:44
Root Cause : 
You must have installed latest node.js and where as your code is still using old node.js

Fix: 
1. Go to your local cloned repo, delete the folder "node_modules"
2. Go to control panel -> add/remove programs -> locate the node.js and un install 
3. go to https://nodejs.org/en/download/ and download the lower version of node.js and try

**Comment by unelige** [comment] 2017-01-13 23:51
Root Cause :
 You must have installed latest node.js and where as your code is still using old node.js

Fix:
1.Go to your local cloned repo, delete the folder "node_modules"
2.Go to control panel -> add/remove programs -> locate the node.js and un install
3.go to https://nodejs.org/en/download/ and download the lower version of node.js and try

*** In my case I had installed v6.9.4 on my windows 10 and faced the above issue. When I re-installed v5.10.1 resolved the issue***

**Comment by Jefiozie** [comment] 2017-03-07 08:46
Hi @andrewmurray  is this issue resolved with above comments?

**Comment by andrewmurray** [comment] 2017-03-27 15:29
Hi, yes it seems to be resolved on my current versions of node & npm, 6.10.0 and 4.1.1 respectively. I have gone back to the LTS versions for other non-associated reasons.
I have also tried at home on the node 7.2 version and it seemed to work fine.
Unfortunately, lots of tests fail following a gulp but I'll raise another ticket for those if my investigations get me nowhere.

**Comment by Jefiozie** [comment] 2017-03-27 18:37
Great so we can close down this issue?

**Comment by andrewmurray** [comment] 2017-03-27 19:49
Yeah, please do. Thanks.

**Closed** 2017-03-28 05:34 UTC
Labels: needs: info

**Comment by RohithKP** [comment] 2017-05-29 15:42
Rather than downgrading node version you can upgrade karma version to solve this issue

```
    "jasmine-core": "latest",
    "karma": "latest",
    "karma-chrome-launcher": "latest",
    "karma-jasmine": "latest"
```

**Comment by riyajk** [comment] 2018-07-30 11:14
@RohithKP  its working nicely
