### ISSUE TITLE
angular ui select form validation

### ISSUE THREAD

**Issue by maniskasyap** [angular-ui/ui-select#1827] opened 2016-10-13 14:59 UTC
I am facing an issue with using the angular ui select in one of my works. Here is the use case:
1. If I focus on the select box pressing tab button, and then tab out of it, should validate.
2. If I click inside select box and then click out of it, should validate.

Here is my html:

``` html
    <div class="form-group col-xs-6" ng-class="{ 'has-error' : engagementDetailsForm.edSolExpert.$invalid && engagementDetailsForm.edSolExpert.$touched }">
      <label for="edSolExpert">Expert</label><sup class="text-r">*</sup>
      <!-- <input type="text" class="form-control input-sm" id="edSolExpert"> -->
      <ui-select multiple ng-model="survey.selected_expert_details" name="edSolExpert" ng-required="!survey.selected_coach_details.length > 0" class="form-control">
        <ui-select-match>{{$item.Name}}</ui-select-match>
        <ui-select-choices repeat="person in names | filter: $select.search track by $index" refresh="getPeople($select.search, $select)" refresh-delay="0" minimum-input-length=3>
          <span ng-bind-html="person.Name | highlight: $select.search"></span>
        </ui-select-choices>
      </ui-select>
      <div class="help-block" ng-messages="engagementDetailsForm.edSolExpert.$error" ng-if="engagementDetailsForm.edSolExpert.$touched">
        <div ng-messages-include="views/common/messages.html"></div>
      </div>
    </div>

```

Which renders to:

``` html

    <div class="form-group col-xs-6" ng-class="{ 'has-error' : engagementDetailsForm.edSolExpert.$invalid &amp;&amp; engagementDetailsForm.edSolExpert.$touched }">
      <label for="edSolExpert">Expert</label><sup class="text-r">*</sup>
      <!-- <input type="text" class="form-control input-sm" id="edSolExpert"> -->
      <div class="form-control ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control ng-invalid ng-invalid-required" ng-class="{open: $select.open}" ng-model="survey.selected_expert_details" name="edSolExpert" ng-required="!survey.selected_coach_details.length > 0"
      required="required">
        <div><span class="ui-select-match"><!-- ngRepeat: $item in $select.selected track by $index --></span>
          <input type="search" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="ui-select-search input-xs ng-pristine ng-untouched ng-valid" placeholder="" ng-disabled="$select.disabled" ng-click="$select.activate()" ng-model="$select.search"
          role="combobox" aria-label="Select box" ondrop="return false;" style="width: 327px;">
        </div>
        <ul class="ui-select-choices ui-select-choices-content ui-select-dropdown dropdown-menu ng-hide" role="listbox" ng-show="$select.open &amp;&amp; $select.items.length > 0" repeat="person in names | filter: $select.search track by $index" refresh="getPeople($select.search, $select)"
        refresh-delay="0" minimum-input-length="3">
          <li class="ui-select-choices-group" id="ui-select-choices-0">
            <div class="divider ng-hide" ng-show="$select.isGrouped &amp;&amp; $index > 0"></div>
            <div ng-show="$select.isGrouped" class="ui-select-choices-group-label dropdown-header ng-binding ng-hide" ng-bind="$group.name"></div>
            <!-- ngRepeat: person in $select.items track by $index -->
          </li>
        </ul>
        <div class="ui-select-no-choice"></div>
        <ui-select-multiple></ui-select-multiple>
      </div>
      <!-- ngIf: engagementDetailsForm.edSolExpert.$touched -->
    </div>

```

Notice, there is no `ng-untouched` class present on `ui-select-container` div. 
Both the use cases above fail:
1. Validation is not triggered at all on `tab` out as validation rule is on `ng-touched` ($touched), which is not added on tab out.
2. Validation is triggered after clicking 2-3 times as `ng-touched` class is added then.

Using-
1. angularjs v1.4.8
2. ui-select Version: 0.19.3
3. angular-ui-bootstrap Version: 0.14.3

Is this a bug or am I missing something here? Thanks.

**Comment by user378230** [comment] 2016-11-23 00:03
Closing as dupe of #1090

**Closed by user378230** 2016-11-23 00:03 UTC
