### ISSUE TITLE
V0.19.7 throws strictdi error

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [angular-ui/ui-select#1971] opened 2017-04-12 15:22 UTC
starting from v0.19.7 I started getting
`Error: [$injector:strictdi] function(uiSelectConfig) is not using explicit annotation and cannot be invoked in strict mode`

**Comment by zuzusik** [comment] 2017-04-12 15:25
I can confirm this.

**Comment by pamigomp** [comment] 2017-04-12 20:37
+1

**Comment by adybionka** [comment] 2017-04-13 11:44
We had the same problem in our project.

**Comment by adybionka** [comment] 2017-04-13 11:44
We have the same problem in our project. Back to 0.19.5.

**Comment by Jefiozie** [comment] 2017-04-18 05:54
Just pushed a new version where I reverted the head/ footer feature hope this will solve all issues.

Please let me know.

**Comment by Jefiozie** [comment] 2017-04-19 16:53
@ivanvoznyakovsky can you verify that the issue is resolved?

**Comment by Jefiozie** [comment] 2017-04-20 05:34
Closing the issue down as I believe this should be resolved and the other issue that open about this problem are resolved. If not please let me know and we will have a further look.

**Closed by Jefiozie** 2017-04-20 05:34 UTC
Labels: needs: info
