### ISSUE TITLE
multiple is not working for me. 

### ISSUE THREAD

**Issue by amit-natani** [angular-ui/ui-select#1665] opened 2016-06-16 07:14 UTC
multiple is not working for me. On plunker it is working fine. But in my application it is not working. Giving Error : "http://localhost:5100/community/selectize/match-multiple.tpl.html"

**Comment by user378230** [comment] 2016-06-16 11:09
Selectize doesn't support multiple (there is not template) 

Closing as duplicate of #295

**Closed by user378230** 2016-06-16 11:09 UTC
