### ISSUE TITLE
 Maximum call stack size exceeded error when the initial array is changed.

### ISSUE THREAD

**Issue by urshree** [angular-ui/ui-select#208] opened 2014-09-22 09:23 UTC
I was initially loading array from my db like this.
`$scope.people = [`
    `{ name: 'Adam',      email: 'adam@email.com',      age: 10 },`
   ` { name: 'Amalie',    email: 'amalie@email.com',    age: 12 },`
  `  { name: 'Wladimir',  email: 'wladimir@email.com',  age: 30 },`
  `  { name: 'Samantha',  email: 'samantha@email.com',  age: 31 }   `
  `];`

Select was rendering with out a problem. If user revisits the same page, i used to load it from cache which had few more proprieties in the array.  

`$scope.people = [`
   ` { name: 'Adam',      email: 'adam@email.com',      age: 10 , gender:'m'},`
   ` { name: 'Amalie',    email: 'amalie@email.com',    age: 12 , gender:'f'},`
    `{ name: 'Wladimir',  email: 'wladimir@email.com',  age: 30,  gender:'m' },`
   ` { name: 'Samantha',  email: 'samantha@email.com',  age: 31,  gender:'f' }  `
  `];`

But, ui-select started throwing "Maximum call stack size exceeded" error recursively.

**Comment by ovmihai** [comment] 2015-10-28 08:14
Is there any solution for this issue ?

**Comment by wesleycho** [comment] 2016-03-27 06:39
Closing due to lack of reproduction via Plunker - feel free to open a new issue with a reproduction based on the current release if this is still a problem.

**Closed by wesleycho** 2016-03-27 06:39 UTC
