### ISSUE TITLE
Select is opened before the scope loaded

### ISSUE THREAD

**Issue by igorkemack** [angular-ui/ui-select#1735] opened 2016-07-22 08:05 UTC
### Bug description:

When site is loading in browser for few moments until the scope is loaded select stay open. The bug only appears when scope watchers number is large (~1000).
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.7
UI-Select:  0.17.1
Select2: 3.4.8
Selectize: 0.12.1

**Comment by Jefiozie** [comment] 2016-07-23 14:26
Hi @igorkemack could you check this also on the last version (0.18.1) and provide a plunkner example?

**Comment by igorkemack** [comment] 2016-07-25 07:47
Hi @Jefiozie , updating ui-select to 0.18.1 not resolved problem.
Sorry, but on small amount of scope watching, select works faster. It's too hard to provide example on plunker to show this bug.

**Comment by Jefiozie** [comment] 2016-07-25 20:35
Hi @igorkemack ,

So I had a look at this issue and it looks like I cannot reporduce this issue. I have made a plunker example with some code you  can use to do some testing.

[Plunker example lot of watchers](http://plnkr.co/edit/a2UwmTzvJl0o5kzz1oze?p=preview)


Can you tell me if you see the same behaviour or what I need to change to reproduce this issue. 
I have counted the watchers and is around + 10.000 watchers.

**Comment by igorkemack** [comment] 2016-07-26 10:23
It's not that problem. Lot of watcher must to be outside of ui-select. I have recordered how it looks like.
[https://www.dropbox.com/s/kgrs7sxijilihwr/ui-select-bug.gif?dl=0](url)

**Comment by Jefiozie** [comment] 2016-08-01 16:47
@user378230  any thoughts on this one?

**Comment by igorkemack** [comment] 2016-08-18 12:20
I think I've found where this problem occures:
<div class="ui-select-dropdown select2-drop select2-with-searchbox select2-drop-active" ng-class="{'select2-display-none': !$select.open}">...</div>

I'm used select2 theme. Just throw error in your controller and you'll see this error.

**Comment by Jefiozie** [comment] 2016-08-18 12:37
Could you share a plunker for this? Without it is really hard to find the cause of this problem

**Comment by igorkemack** [comment] 2016-08-19 07:44
[Plnkr](http://plnkr.co/edit/35zTPWzOLR7p7DI2LPzg?p=preview)

**Comment by Jefiozie** [comment] 2016-08-19 18:51
I see the error  but I don't see the behaviour you have described in the initial comment.  Please try and setup a plunker where the issue as described is reproducable.

@user378320 maybe you have seen this?

**Comment by user378230** [comment] 2016-11-23 00:05
Closing due to lack of repro example.

**Closed by user378230** 2016-11-23 00:05 UTC
