### ISSUE TITLE
on-select first time

### ISSUE THREAD

**Issue by lixsouille** [angular-ui/ui-select#573] opened 2015-01-10 14:09 UTC
Hi I wrote this code using ui-select

        <div ui-select ng-model="entityInfo.entity_country" on-select="countryChange(entityInfo.entity_country)"  theme="selectize" style="width: 300px;">
            <div ui-select-match placeholder="Select or search a country in the list...">
                <img ng-src="{{$select.selected.country_flag}}"/>
                {{$select.selected.country_name}} ({{$select.selected.country_currency}})
            </div ui-select-match>
            <div ui-select-choices repeat="country in countryList | filter: $select.search">
                <img ng-src="{{country.country_flag}}"/>
                <span ng-bind-html="country.country_name | highlight: $select.search"></span>
            </div ui-select-choices>
        </div ui-select>

However when i first select a value passed is undefined (entityInfo.entity_country) the function on-select . When I change after for the second time the value is good?

Do you have any idea why?

Thank you

**Comment by tholford** [comment] 2015-01-16 00:03
+1, also experiencing this issue

**Comment by jihunleekr** [comment] 2015-09-14 02:20
+1, also experiencing this issue.

**Comment by wesleycho** [comment] 2016-03-27 17:19
Can you post a reproduction in Plunker based on the latest release?

**Comment by user378230** [comment] 2016-08-25 23:31
Closing due to lack of repro.

**Closed by user378230** 2016-08-25 23:31 UTC
Labels: needs: plunkr
