### ISSUE TITLE
Backspace "feature" blocking obligatory selects

### ISSUE THREAD

**Issue by Icydillic** [angular-ui/ui-select#525] opened 2014-12-17 08:14 UTC
Hey all,

I understand that there is a need to use backspace to delete the selection input.
But is it possible to give it a config in the directive?
In this scenario I do not see a possibility to make a select option obligatory or am I missing something? Should I use the on-select="" property to supress an empty selection?

Kind regards,
Stefan

**Comment by wesleycho** [comment] 2016-03-27 17:06
This should probably be implemented in the library through proper validation measures.

I'm going to close this as a duplicate of the other validation issues currently open.

**Closed by wesleycho** 2016-03-27 17:06 UTC
