### ISSUE TITLE
Automatic open dropdown when tab key to it

### ISSUE THREAD

**Issue by hotanlamvnn** [angular-ui/ui-select#710] opened 2015-03-02 11:07 UTC
how??? automatic open dropdown ui-select (theme: select2) when tab key to it...
please help me.

**Comment by hotanlamvnn** [comment] 2015-03-09 07:59
please

**Comment by wesleycho** [comment] 2016-03-27 20:42
Closing due to lack of details/reproduction/clear english.

**Closed by wesleycho** 2016-03-27 20:42 UTC
