### ISSUE TITLE
Nice to have: .select2-search input {background-image}  reflect refresh() action in progress

### ISSUE THREAD

**Issue by dimylik** [angular-ui/ui-select#1636] opened 2016-06-02 12:25 UTC
Nice to have indicator, that refresh() action is in progress, instead of magnifying glass, show something like loading icon in search input.
This will indicates that something is going on.

Also, you could extend that, and if refresh() action does not return anything, show another icon, like cross or something

like:

.select2-search .refresh-in-progress input {
   background-image: url('loading.gif')
}  

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.49

UI-Select: "0.17.1"

Bootstrap: 3

**Comment by user378230** [comment] 2016-06-03 09:13
Closing as duplicate of #919

**Closed by user378230** 2016-06-03 09:13 UTC
