### ISSUE TITLE
Erase current selected object when input is blank

### ISSUE THREAD

**Issue by bettercallsteve** [angular-ui/ui-select#516] opened 2014-12-15 22:33 UTC
Newguy here, 

I noticed that my users are trying to clear a current selected item by clicking on the ui-select, clearing the search box and then clicking out / escaping / hitting enter. This keeps the current item selected even though the search box is empty. Even with a delete button at the end of the input field, it still creates an awkward experience for the user as it does not perform as expected.

I think that there should be an option to clear the ng-model when the search box is empty and the user escapes the input.

For example, search for anything into the first ui-select in this plunker:

http://plnkr.co/edit/a3KlK8dKH3wwiiksDSn2?p=preview

After you've selected something, click on the ui-select again, and delete the search selection. Then, click outside of the input box. The previously selected item will appear again, even though this goes against what a user would expect to happen.

I have attempted to fix this on my own build but I lack the experience to properly do it. If anyone could help me figure this one out that would be great.

Thank you!

**Comment by rapmue** [comment] 2015-04-08 11:11
+1, I expirienced the same.

**Comment by wesleycho** [comment] 2016-03-27 17:00
Closing this as a duplicate of #367

**Closed by wesleycho** 2016-03-27 17:00 UTC
