### ISSUE TITLE
missing classes in <i> element of match.tpl.html in bootstrap theme of ui-select

### ISSUE THREAD

**Issue by armbp1972** [angular-ui/ui-select#1565] opened 2016-04-18 11:28 UTC
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

I have just upgraded my project to angular 1.5.4 and ui-select 0.16.0 and the down-arrows disappeared from the ui-select components in all the pages. I tracked down the issue and found that in line 2079, column 715 of "select.js", now is missing the classes "fa fa-angle-down", so I restored that and the down-arrows are there again. It's a bug or something in the code I'm missing here?
 
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.5.4

UI-Select: 0.16.0

Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by user378230** [comment] 2016-04-18 12:29
Hi! As requested in the issue template can you please provide:
>Link to minimally-working plunker that reproduces the issue:

As far as I can see this is not an issue in the latest version. (v0.16.1 - _note: only the latest version of the library is supported/maintained_)

For example: http://angular-ui.github.io/ui-select/demo-bootstrap.html (from http://angular-ui.github.io/ui-select/#examples)

If you can provide a reproduction plunkr then we can investigate. 

Thanks!

**Comment by armbp1972** [comment] 2016-04-18 13:10
Sorry, I've checked out your 0.9.9 version (the previous one we were using before upgrading) and those classes (fa fa-angle-down) are not there, so it looks like if in my project some other colleague had added them to the source code in order to customize the component. I'm going to check with them and if that's the case I tell you guys.

**Comment by user378230** [comment] 2016-04-18 15:34
Thinking about it more, `fa` and `fa-angle-down` appear to be `fontawesome` icons, we don't have any dependency on fontawesome (since we use bootstrap glyphicons for the `caret`). 

Going to close this as its a usage issue and not a bug.

**Closed by user378230** 2016-04-18 15:34 UTC
Labels: needs: info, question

**Comment by armbp1972** [comment] 2016-04-18 15:37
Yes, definitely you are right. Sorry for the mistake.
