### ISSUE TITLE
Call "Group-Refresh" manually

### ISSUE THREAD

**Issue by hoppler** [angular-ui/ui-select#565] opened 2015-01-05 18:25 UTC
Hi,

is there a function to manually call "group-refresh". By that i mean, that the ```group-by="modelGrouping()"``` is called and my items are gettin grouped again?
The reason for this is, that i have a property on all my items sayin its a "suggestion" or not and if its a "suggestion" it should be moved into the "suggestion" group.
Currently im tricking the ```"Line 275:       $scope.$watchCollection(ctrl.parserResult.source, function(items) " ``` by deepCloning my whole array. so the ```modelGrouping()``` function gets called.

# Jade-Code (every indent is an inner item)
```jade
ui-select(ng-model='view.model.elementId', name="modelName")
	ui-select-match {{$select.selected.name}}
	ui-select-choices(group-by="modelGrouping", repeat='iElement.value as iElement in intern.elementList | filter: $select.search')
		.row
		   .col-md-8(ng-bind-html='iElement.name | highlight: $select.search')
		   .col-md-4 Volumen: {{ iElement.capacity }}
```

# Javascript-Code
```javascript
$scope.suggestionChange = function(){
	modelService.getSuggestions($scope.view.model).success(function(suggestions){
		if(angular.isUndefined(suggestions) ||
			!angular.isArray(suggestions) ||
			suggestions.length === 0){
			$scope.intern.suggestionList = [];
			return;
		}
		$scope.intern.suggestionList = suggestions;
		$scope.intern.elementList = [];
		$scope.intern.elementList = _.clone($scope.view.elementList, true);
	});
};

$scope.modelGrouping = function (item){
	item.isSuggestion = _.contains($scope.intern.suggestionList, item.value);
	if(item.isSuggestion) {
		return ' Suggestions';
	}
	return item.type;
};
```

Thanks in advance
Mike

**Comment by hoppler** [comment] 2015-02-17 20:21
Push

**Comment by dimirc** [comment] 2015-02-17 21:57
Will be better if you setup a Plunker trying to explain this

**Comment by wesleycho** [comment] 2016-03-27 17:20
Closing due to lack of Plunker. Feel free to open a new issue with reproduction based on the latest release if this is still an issue.

**Closed by wesleycho** 2016-03-27 17:20 UTC
