### ISSUE TITLE
Is there any way to set placeholder with search-enabled="false"?

### ISSUE THREAD

**Issue by mackenrou** [angular-ui/ui-select#241] opened 2014-09-30 15:14 UTC
This is my code:
`<ui-select ng-model="data.selectEstablec" theme="selectize" search-enabled="false" style="width: 95%;">`
`<ui-select-match placeholder="Establecimiento...">{{$select.selected.nombre}}</ui-select-match>`
`<ui-select-choices repeat="est in establecimientos" value="{{est.id}}">{{est.nombre}}</ui-select-choices>`
`</ui-select>`
When search is enabled, placeholder shows fine.

I tested this also:
`<ui-select ng-model="data.selectEstablec" theme="selectize" search-enabled="false" data-placeholder="Establecimiento..." style="width: 95%;">`
`<ui-select-match>{{$select.selected.nombre}}</ui-select-match>`
`<ui-select-choices repeat="est in establecimientos" value="{{est.id}}">{{est.nombre}}</ui-select-choices>`
`</ui-select>`
But placeholder is missing.

**Comment by wesleycho** [comment] 2016-03-27 06:53
Closing due to age of issue - feel free to open a new issue with reproduction based on the latest release if this is still a problem.

**Closed by wesleycho** 2016-03-27 06:53 UTC
