### ISSUE TITLE
Already selected item not clear when refresh items

### ISSUE THREAD

**Issue by barmaglot92** [angular-ui/ui-select#1041] opened 2015-06-25 08:07 UTC
406 line:
//Remove already selected items (ex: while searching)
          //TODO Should add a test
          ctrl.refreshItems(items);
          ctrl.ngModel.$modelValue = null; //Force scope model value and ngModel value to be out of sync to re-run formatters

but model binded in <ui-select ng-model=""> not clear, ctrl.ngModel.$modelValue = null - not affected on model in my contoller.

**Comment by wesleycho** [comment] 2016-03-27 23:04
Closing due to lack of actionable information - feel free to open a new issue with appropriate reproduction and detailed information about the situation if this is still an issue.

**Closed by wesleycho** 2016-03-27 23:04 UTC
