### ISSUE TITLE
[ngRepeat:Duplicates] Multi select with ngResource objects AND refresh

### ISSUE THREAD

**Issue by mjquinlan2000** [angular-ui/ui-select#864] opened 2015-04-17 15:55 UTC
I've run into an interesting bug while using this wonderful library at work. Here's my problem:

I have an edit view for one object within my application. I go to the page and the object gets requested from the server. Let's say that it's a Person object. This Person object has many Sport objects associated with it that are attached under `person.sports`. My server also serves up Sport objects from a different endpoint through which I would like to populate my select dropdown with. There are far too many Sports to request from the server so I need to use the refresh option for my `ui-select-choices`. Everything is requested by `ngResource`. So when I have the person object loaded onto the page I populate the ui select with sports that already exist on the Person object.

The problem is that you are somehow allowed to search for the same sport (and have it appear in the select dropdown) regardless of wether or not the sport has already been attached to the person. When you select the sport that has already been attached, you get the all to familiar `ngRepeat:Duplicates` error due to the `track by` that has been attached to the `ui-select-choices` directive. After further investigation, I have realized that this is due to the fact that the Sport objects are being cast to an `ngResource` object as opposed to the generic JavaScript `Object`. This is not an issue, however, when I convert the Sport back to a generic `Object`. I've created a plunker with some detailed instructions to better explain the issue:

http://plnkr.co/edit/Tl81DlBVAgxYRscsquh7?p=preview

I've currently got a workaround for it, so it's only a little bit annoying. I'm going to try to dive into the source code if I can get away from work for a bit. Let me know if you guys have any further questions about what I'm seeing.

Thanks!

**Comment by SelrahcD** [comment] 2015-05-05 15:50
Hi @mjquinlan2000 !
I ran into a similar issue. When a search is made and then deleted elements are displayed twice. I tried to add the `track by` but then I got the duplicates error too.

Could you tell me what your workaround is while a fix is being found by the team ? :)

**Comment by mjquinlan2000** [comment] 2015-05-06 13:21
Well I don't know if this will apply to what you're looking for, but on the success of the request that gets the sports for the dropdown I coerce the `ngResource` into regular JavaScript Objects. Basically the success callback looks something like this (I use underscore.js too):

```javascript
function(sports){
  scope.dropdownObjects = _.map(sports, function(sport){
    // The following line will create a new `Object` instance with just id and name which
    // is all my server needs to attach a sport event
    return _.pick(sport, 'id', 'name');
  });
}
```

Hope that helps!

**Comment by wesleycho** [comment] 2016-03-27 21:47
Closing as a duplicate of #366.

**Closed by wesleycho** 2016-03-27 21:47 UTC
