### ISSUE TITLE
Failed to load template - match-multiple.tpl.html/choices.tpl.html

### ISSUE THREAD

**Issue by samuelcastro** [angular-ui/ui-select#324] opened 2014-10-17 14:07 UTC
From the documentation - I just needed to reference select.js and select.css, but I'm receiving that error:

GET http://localhost:8888/ui/select2/match-multiple.tpl.html?authtoken=54410bf983231:default 404 (Not Found) angular.js:8495
GET http://localhost:8888/ui/select2/select-multiple.tpl.html?authtoken=54410bf983231:default 404 (Not Found) angular.js:8495
GET http://localhost:8888/ui/select2/choices.tpl.html?authtoken=54410bf983231:default 404 (Not Found) angular.js:8495
Error: [$compile:tpload] http://errors.angularjs.org/1.2.20/$compile/tpload?p0=select2%2Fchoices.tpl.html
    at Error (native)
    at http://localhost:8888/ui/js/libs/angular.js:6:450
    at http://localhost:8888/ui/js/libs/angular.js:61:181
    at http://localhost:8888/ui/js/libs/angular.js:72:286
    at w (http://localhost:8888/ui/js/libs/angular.js:100:39)
    at w (http://localhost:8888/ui/js/libs/angular.js:100:39)
    at http://localhost:8888/ui/js/libs/angular.js:101:295
    at k.$eval (http://localhost:8888/ui/js/libs/angular.js:111:353)
    at k.$digest (http://localhost:8888/ui/js/libs/angular.js:108:419)
    at k.$apply (http://localhost:8888/ui/js/libs/angular.js:112:173) angular.js:9997
Error: [$compile:tpload] http://errors.angularjs.org/1.2.20/$compile/tpload?p0=select2%2Fmatch-multiple.tpl.html
    at Error (native)
    at http://localhost:8888/ui/js/libs/angular.js:6:450
    at http://localhost:8888/ui/js/libs/angular.js:61:181
    at http://localhost:8888/ui/js/libs/angular.js:72:286
    at w (http://localhost:8888/ui/js/libs/angular.js:100:39)
    at w (http://localhost:8888/ui/js/libs/angular.js:100:39)
    at http://localhost:8888/ui/js/libs/angular.js:101:295
    at k.$eval (http://localhost:8888/ui/js/libs/angular.js:111:353)
    at k.$digest (http://localhost:8888/ui/js/libs/angular.js:108:419)
    at k.$apply (http://localhost:8888/ui/js/libs/angular.js:112:173) 

Same error here: http://stackoverflow.com/questions/25951919/angular-ui-select-error

What is happening?

**Comment by premchandrasingh** [comment] 2015-02-27 13:50
Problem is still there with both minified and non-minified version. No luck with "theme" attribute. Tried with angular 1.2.9 and 1.3.xx

**Comment by wtw** [comment] 2015-03-02 20:16
I too had this problem, but I was using an `httpInterceptor` and the templates were accessed under a different address, cache was bypassed and they were requested from the server. So in addition to the `noCacheInterceptor ` mentioned by @bashanam, you might want to check if you fiddle with the request.

**Comment by dimirc** [comment] 2015-03-03 04:19
Can you setup a plunker to check your issue?

**Comment by rahulgiri** [comment] 2015-10-08 14:12
I have the seme problem with interceptor. 

I have updated the condition in interceptor to ignore the request as below and its work for me.

condition : !config.url.match(/^template\//) && !config.url.match(/\.html/)

Hope this will works for you.. :)

**Comment by wesleycho** [comment] 2016-03-27 07:07
Closing due to lack of reproduction via Plunker - feel free to open a new issue with a reproduction in Plunker based on the latest release if this is still a problem.

**Closed by wesleycho** 2016-03-27 07:07 UTC

**Comment by geri777** [comment] 2016-09-02 22:35
I have the same problem. It tries to load **/bootstrap%20/match.tpl.html** and **/bootstrap%20/choices.tpl.html**.
My code has been working for months - I don't know what has changed. I am using the box inside of a template like this:

```
<script type="text/ng-template " id="popup.html ">
... html code here
</script>
```

I anyone reads this and has an idea... please write back.

**Comment by brk114** [comment] 2018-10-24 06:37
Using CDN for select2.js gave me this issue, so i have added templateCache in my module js file
``` javascript
angular.module('ui.select').run(['$templateCache', function($templateCache) {
  $templateCache.put(
                'selectize/match-multiple.tpl.html',
                '<div class="ui-select-match" data-value="" ng-repeat="$item in $select.selected track by $index" ng-click="$selectMultiple.activeMatchIndex = $index;" ng-class="{\'active\':$selectMultiple.activeMatchIndex === $index}" ui-select-sort="$select.selected"><span class="ui-select-match-item" ng-class="{\'select-locked\':$select.isLocked(this, $index)}"><span uis-transclude-append=""></span> <span class="remove ui-select-match-close" ng-hide="$select.disabled" ng-click="$selectMultiple.removeChoice($index)">&times;</span></span></div>'
  );
  $templateCache.put(
                'selectize/select-multiple.tpl.html',
                '<div class="ui-select-container selectize-control multi plugin-remove_button" ng-class="{\'open\': $select.open}"><div class="selectize-input" ng-class="{\'focus\': $select.open, \'disabled\': $select.disabled, \'selectize-focus\' : $select.focus}" ng-click="$select.open && !$select.searchEnabled ? $select.toggle($event) : $select.activate()"><div class="ui-select-match"></div><input type="search" autocomplete="off" tabindex="-1" class="ui-select-search" ng-class="{\'ui-select-search-hidden\':!$select.searchEnabled}" placeholder="{{$selectMultiple.getPlaceholder()}}" ng-model="$select.search" ng-disabled="$select.disabled" aria-expanded="{{$select.open}}" aria-label="{{ $select.baseTitle }}" ondrop="return false;"></div><div class="ui-select-choices"></div><div class="ui-select-no-choice"></div></div>'
  );
}]);
````

this solved my issue.
