### ISSUE TITLE
tab out doesn't hide filter text

### ISSUE THREAD

**Issue by lvostinar** [angular-ui/ui-select#1242] opened 2015-10-12 08:16 UTC
See:  http://plnkr.co/edit/Yyvw3lRPJMQzqBwzuEjG?p=preview

If I type some text in filter then tab out (and there are no matching results) the filter remains visible. If I do same thing but I click outside it works well.

Any thoughts how this should be fixed?

**Comment by samih-dev** [comment] 2015-12-29 08:51
+1 
In my case I'm using multiple selection mode with tagging, I see x button tagged alone, without text. 
Using mouse click to focus out, the input value get deleted (again if the filtered text isn't exist) and not tag added - this should be the same behavior when pressing TAB.

**Comment by user378230** [comment] 2016-01-27 16:52
Duplicate of #367

**Comment by wesleycho** [comment] 2016-03-28 03:18
Closing as a duplicate as per comment

**Closed by wesleycho** 2016-03-28 03:18 UTC
