### ISSUE TITLE
ui-select doesn't show select-choices in modal window from $scope array of objects

### ISSUE THREAD

**Issue by Exiliot** [angular-ui/ui-select#1100] opened 2015-07-22 07:55 UTC
I faced with such problem: ui-select doesn't work normally in Angular-Bootstrap modal window if the array of objects for select-choices is defined directly in the modal controller. If the array is returned by $http request - ui-select works good. Why is it so?

**Comment by lugithub** [comment] 2015-07-31 16:09
i have the same problem.

**Comment by dimirc** [comment] 2015-08-01 00:37
Can you setup a plunker?

**Comment by krtek** [comment] 2015-08-07 00:30
I can confirm this bug too.

**Comment by jbonigomes** [comment] 2015-08-11 14:11
+1

**Comment by jbonigomes** [comment] 2015-08-11 14:37
I know this is a hack, but @DeezCashews temporary solution is working for me:

https://github.com/angular-ui/ui-select/issues/1126

**Comment by krtek** [comment] 2015-08-11 14:48
@jbonigomes Thanks! This workaround works.

**Comment by jbonigomes** [comment] 2015-08-11 14:58
Great stuff @krtek

**Comment by DeezCashews** [comment] 2015-08-11 16:19
Glad it could help.  If you get a chance please upvote at http://stackoverflow.com/questions/29893423/angular-ui-select-is-not-displaying-the-list-of-options-when-included-in-angular/31886971#31886971 so others can find solution easier on SO.

**Comment by jbonigomes** [comment] 2015-08-11 16:28
yes @DeezCashews, will do

**Comment by captify-ddavydov** [comment] 2015-08-14 11:32
Error occurs here in select.js:
(line 610: ctrl.searchInput.css('width', '10px');)

In this case input tag has width: 10px. You can click in this 10px-area - and it will work. As we use this lib via bower - I've fix it without touching source in the following way:

<ui-select-match 
  placeholder="placeholder..." 
  ng-class="{empty: !account.roles.length}">
    {{::$item.name}}
</ui-select-match>
so, if model array is empty - just make width of input 100%. We use 'select2' theme

.empty.ui-select-match + .select2-search-field,
.empty.ui-select-match + .select2-search-field input{
    width: 100% !important;
}

**Comment by jbonigomes** [comment] 2015-08-14 12:29
thanks @captify-ddavydov this also works for me

**Comment by wesleycho** [comment] 2016-03-27 23:24
Closing due to lack of reproduction in Plunker - feel free to open a new issue if this is still a problem with reproduction.

**Closed by wesleycho** 2016-03-27 23:24 UTC

**Comment by vylan** [comment] 2017-10-19 14:50
Met this problem too, all the above solutions didn't work for me. I fixed it by replace the isNil function in the source code with:
`function isNil(value) {
  return angular.isUndefined(value) || value === null || !Object.keys(value).length;
}`

**Comment by ghost** [comment] 2018-03-09 03:36
I also met this problem while using ui-modal and I solve this using 'ng-class' condition to the `ui-select-choices` directive:

**modal.html**
```
<ui-select ng-model="person.selected" theme="bootstrap" on-select="onSelect($item)" ng-click="select_open = true">
    <ui-select-match placeholder="制作者">{{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="item in people | propsFilter: {name: $select.search, email: $select.search}" ng-class="{ 'select_open': select_open }">
        <div ng-bind-html="item.name | highlight: $select.search"></div>
        <small ng-bind-html="item.email | highlight: $select.search"></small>
    </ui-select-choices>
    <ui-select-no-choice>
        一致するものは見つかりませんでした。
    </ui-select-no-choice>
</ui-select>
```

**app.js**
```
$scope.onSelect = function(item) {
    $scope.open_select = false;
	}
```

**style.css**
```
.select_open {
	opacity: 1 !important;
}
```

Hope it helps. 👍
