### ISSUE TITLE
on-select => $select.search, canceling close-on-select

### ISSUE THREAD

**Issue by katsos** [angular-ui/ui-select#1842] opened 2016-10-31 13:48 UTC
Let's start with that `reset-search-input="true"` doesn't work at all.
Using `close-on-select` and `on-select="resetInput($select)"`  with
`resetInput($select) { $select.search = ''; }` resets the input but cancels the functionality of `close-on-select`.
I came up with this solution `resetInput() { $('input').val(''); }`

Angular: 1.5.0
UI-Select: 0.14.8
Bootstrap: 3.3.6
Select2: 3.5.1

**Comment by Jefiozie** [comment] 2016-11-02 07:06
Hij @katsos, van you verify if the problem is stil present in the last version? If so can you add a plunker for reproduction?

**Comment by Jefiozie** [comment] 2016-11-04 20:31
Any updates?

**Comment by katsos** [comment] 2016-11-04 21:17
Sorry, didn't have time. I will update it as soon as possible.

**Comment by user378230** [comment] 2016-11-05 14:45
Closing for now, please reopen when tested against the latest version and with plunkr that reproduces your issue, as requested in the issue template. 

Thank you! 😄

**Closed by user378230** 2016-11-05 14:45 UTC

**Comment by katsos** [comment] 2016-11-05 14:48
@Jefiozie http://plnkr.co/edit/kTAhzWT150eazlTUsnzv?p=preview
no this bug doesn't appear in the latest version.
