### ISSUE TITLE
Append skipFocusser argument of select as option

### ISSUE THREAD

**Issue by FSou1** [angular-ui/ui-select#401] opened 2014-11-14 15:31 UTC
After i select item (with mouse click) from drop down list, focus still stay on select2, because ng-click callback function now doesn't pass skipFocusser argument in $select.select:

attr('ng-click', '$select.select(' + $select.parserResult.itemName + ')')

In this case, i have to use it like this:

.attr('ng-click', '$select.select(' + $select.parserResult.itemName + ', true)');

**Comment by wesleycho** [comment] 2016-03-27 15:42
Closing as a duplicate of a couple of issues - #432 looks like the most robust one.

**Closed by wesleycho** 2016-03-27 15:42 UTC
