### ISSUE TITLE
Bug, input button & select button showing different rows 

### ISSUE THREAD

**Issue by ntvsx193** [angular-ui/ui-select#554] opened 2014-12-28 00:22 UTC
![screenshot](http://monosnap.zanozahost.ru/2014-12-28_01_06686d.jpg)

2 buttons have class `col-sm-` & `col-md-`
It's make conflict in css.
Use only one: `col-sm-` or `col-md-`

**Comment by zavidovych** [comment] 2015-01-09 19:42
this is not a bug but intended behavior - sm and md both add up to 12. you need to make sure that your container is 100% width and with no padding/margin: http://stackoverflow.com/questions/25178130/why-is-bootstrap-pushing-last-column-on-next-line

**Comment by brianfeister** [comment] 2015-01-12 20:56
We've dropped the ugly bootstrap column usage in v0.9.6.  Closing as dupe of #503.

**Closed** 2015-01-12 20:56 UTC

**Comment by zavidovych** [comment] 2015-01-13 02:46
now allow-clear is broken with theme="bootstrap"...

http://plnkr.co/edit/yzoAL0PRkOyGHeuMbGj2?p=preview

![unkjfgzpb8](https://cloud.githubusercontent.com/assets/1755574/5715277/4a741a0c-9a8b-11e4-9ecb-d2a191d56c6e.png)
