### ISSUE TITLE
No Results Found Message

### ISSUE THREAD

**Issue by KatelynL** [angular-ui/ui-select#831] opened 2015-04-07 18:37 UTC
Is is possible to add in a message for when no results are found in the search?  I believe the original select2 and selectize included this is as a feature.

**Comment by brightcode** [comment] 2015-04-08 12:37
I also missed this. Select2 shows the following when no results match the search:
 
    <ul class="select2-results">
      <li class="select2-no-results">No matches found</li>
    </ul>

**Comment by amcdnl** [comment] 2015-04-09 04:06
I was thinking we should have new 3 options:

- Search placeholder text ( different from input )
- No results text 
- Ajax searching text

@dimirc thoughts?

**Comment by jitendersandhu** [comment] 2015-12-22 20:27
+1

**Comment by sridharthumma** [comment] 2016-01-26 10:06
+1

**Comment by wesleycho** [comment] 2016-03-27 21:30
Closing as a duplicate of #152

**Closed by wesleycho** 2016-03-27 21:30 UTC
