### ISSUE TITLE
Single select with refresh doesnt work. Input is hidden!?

### ISSUE THREAD

**Issue by ev45ive** [angular-ui/ui-select#764] opened 2015-03-16 15:33 UTC
I try to make single select populated async with refresh="searchResults($select.search)" and it doesnt work. Input doesnt show. Its ng-hiden ( ng-show="$select.searchEnabled && $select.open" )
I have no select-enabled option set, so why it behaves so weird? Also its bootstrap theme so it should allow search instantly not after dropdown is shown as select2/selectivize.

No errors, no clue. Also Examples doesnt show correct single item with refresh="", async example is bad as prefetching data before user types anything is not autocomplete. Please help and maybe lets update docs/examples because second time It takes forever to get it running. Thanks!
```
<ui-select style="display:inline-block;width: 300px; border:0;" ng-model="person.selected"
         theme="bootstrap"
         ng-disabled="disabled"
         on-select="select($item)"
         reset-search-input="false">

<ui-select-match placeholder="Enter a full name...">{{$select.selected.full_name}}</ui-select-match>
<ui-select-choices repeat="item in results track by item.id"
         refresh="searchResults($select.search)"
         refresh-delay="0">
  <div ng-bind-html="item.full_name | highlight: $select.search"></div>
</ui-select-choices>
</ui-select>
```

**Comment by dimirc** [comment] 2015-03-17 04:13
Can you setup a plunker with this?

**Comment by wesleycho** [comment] 2016-03-27 20:54
Closing due to lack of reproduction. Feel free to open a new issue with reproduction based on the latest release if it is still an issue.

**Closed by wesleycho** 2016-03-27 20:54 UTC

**Comment by xDisfigure** [comment] 2017-03-24 16:18
@ev45ive If you have found the answer, please stop leaving your issue and tell how you solve this. It will help a lot of people I think.
