### ISSUE TITLE
loading remote items with _ and ? as serach keywords

### ISSUE THREAD

**Issue by Exlord** [angular-ui/ui-select#1777] opened 2016-08-22 06:12 UTC
I am using a php/mysql backend to load data to my select list when user enters a keyword, so far so good, it works. 

But i want to be able to use characters like `_` and `?` in my search parameters which translates to `any length of any characters` and `a single character` in mysql `LIKE '%keyword%'` query.

My query is OK and its working and i can see the data returned in firebug, but `ui-select` shows the `no match found` message. This used to work correctly with the original `select2 jquery comonenets`.

I am guesting that the returned data from the database is filtered again with the angular's filter which threats `_` and `?` as normal characters and therefor does not match anything in the returned list.

So i think this is a bug and the data already filtered by the server should not be filtered again in the client.

**Comment by user378230** [comment] 2016-08-22 10:22
Please provide a plunkr or similar as requested in the issue template.

**Comment by Exlord** [comment] 2016-08-22 13:24
http://plnkr.co/edit/0d3nYm0qzxOPiNJmMqa3

**Comment by user378230** [comment] 2016-08-22 15:37
If I understand correctly you want to treat `_` and `?` as wildcards?

But you are using [angular's `filter` filter](https://docs.angularjs.org/api/ng/filter/filter) in your repeat:
```
<ui-select-choices ... repeat="item.id as item in (items | filter: $select.search) track by item.id">
                                                           ^^^^^^^^^^^^^^^^^^^^^^
```
Which does not support wildcard matching. 

You probably need to make your own angular filter for your use case. 

Closing, as not a bug.

**Closed by user378230** 2016-08-22 15:37 UTC

**Comment by Exlord** [comment] 2016-08-23 04:26
Ohhhhhhh, whoooops, I feel so stupid right now, i copy pasted the code from the examples and totally forgot to remove the filter from the repeat :laughing:
