### ISSUE TITLE
ctrl.select does not trigger

### ISSUE THREAD

**Issue by TheCodeDestroyer** [angular-ui/ui-select#546] opened 2014-12-23 12:55 UTC
The "select" function of select.js does not trigger on click. It does when I press Enter key, but not when I click on an item.
Although the ng-click attribute is present on item div, it looks like this:
`ng-click="$select.select(line,false,$event)"`

No matter what I do it does not trigger...
I'm using Angular 1.3.9 and ui-select 0.9.5.

**Comment by txtbits** [comment] 2015-01-02 11:35
I have the same issue in Chrome, working in Firefox (angular-1.3.4). It works in another app with 75% of same code, i'm trying to figure out whats the problem.

**Comment by seiyria** [comment] 2015-01-05 16:03
Anecdotal bit from me as well: When I was testing on chrome 39, I was testing originally from 127.0.0.1, but when I went to my actual IP, the click action worked. I have no idea how this would or should affect the situation, but it definitely works for me in chrome if I'm not on 127.0.0.1.

**Comment by eostis** [comment] 2015-01-06 09:11
I found a workaround.

I used to have the same issue, only on chrome/OSX. Firefox and Safari worked fine.
In fact, demos work fine, but as soon as I embed the select in my own code, it failed.

My workaround is to deactivate the event 'ng-mouseenter' on line:
.attr('ng-mouseenter', '$select.setActiveItem('+$select.parserResult.itemName +')')

(I replaced 'ng-mouseenter' by the fake event 'XXXXXXng-mouseenter')

Hope it will help.

**Comment by astrism** [comment] 2015-01-12 06:18
I'm having the same issue as well, still trying to debug but same symptoms. Also even if I use Enter to trigger the select, it wont fire my onSelect method.
Also, I tried @eostis solution, didn't work in my case.

**Comment by frankhock** [comment] 2015-01-13 19:37
I'm experiencing the same issue, works in firefox but not chrome 39.0.2171.95

**Comment by txtbits** [comment] 2015-01-14 08:16
In my case it has returned to work properly after disabling Batarang extension. I could not even check that it is interfering.

**Comment by astrism** [comment] 2015-01-14 09:52
@txtbits good find! This fixes the issue for me as well, I see it's also mentioned here in Batarang's issues: https://github.com/angular/angularjs-batarang/issues/173

**Comment by TheCodeDestroyer** [comment] 2015-01-14 09:57
Dear god that's why it worked for me in new Chrome browser. Just enabled batarang in this one and its broken again.

@txtbits nice find!

**Comment by astrism** [comment] 2015-01-15 06:57
Several strange things when I have Batarang turned on:
* The demo plunkrs work fine for me when testing this issue on the plunkr site.
* This bug only comes up on localhost for me, anyone else experience the issue in a live environment? Possibly why the plunkr works fine...
* When I download the demo plunkr and run it using file:// no problems. But when I launch a server it breaks and run on localhost, it breaks.

**Comment by seiyria** [comment] 2015-01-15 13:03
For me, it only happens on localhost. When I access my pages via external
IP, it works fine.

**Comment by andrewMuntyan** [comment] 2015-01-27 20:44
@txtbits thanks for advise. It works for me =)

**Comment by eostis** [comment] 2015-01-27 21:05
@txtbits worked also :)

**Comment by Fuhrmann** [comment] 2015-05-07 15:14
@txtbits Worked here too! Thanks.

**Comment by samidarko** [comment] 2015-05-15 05:32
@txtbits thanks mate :)

**Comment by ibigbug** [comment] 2015-05-18 09:11
:+1:

**Comment by rzimmer06** [comment] 2015-10-22 19:37
@astrism Did you ever figure out how to get enter to call the select function? I currently have the angular batarang disabled and when i use tab or enter with an item highlighted, it will not call my on-select function.

**Comment by wesleycho** [comment] 2016-03-27 17:09
Closing as a batarang bug.

Any other issues should have new issues with appropriate reproduction in Plunker.

**Closed by wesleycho** 2016-03-27 17:09 UTC
