### ISSUE TITLE
"No results" for select2 theme

### ISSUE THREAD

**Issue by kanwei** [angular-ui/ui-select#121] opened 2014-07-25 02:26 UTC
select2 supports displaying of a message when there aren't any results. I'm working on a patch to enable this.

```<li ng-show="$select.search && !$select.items.length" class="select2-no-results"></li>````

**Comment by MBentley1976** [comment] 2015-02-12 20:08
+1 to this.  I'm going to have to see if I can wrap something around the ui-select directive in order to support this throughout my application.  It would be great if there was a directive under the ui-select directive that I could define.

**Comment by caseahr** [comment] 2015-03-06 17:16
+1

**Comment by junajan** [comment] 2015-04-17 12:29
+1

**Comment by fabiopaiva** [comment] 2015-10-14 19:43
Alternatively

    <ui-select> 
        <ui-select-match>
            {{$select.selected}}
        </ui-select-match>
        <ui-select-choices repeat="option in options | filter: $select.search" refresh="refreshOptions($select.search)" refresh-delay="500">
            <div ng-bind-html="option | highlight: $select.search"></div>
        </ui-select-choices> 
    </ui-select>
    <div class="text-warning" ng-if="options.length == 0">Nothing found</div>

**Comment by nadavsinai** [comment] 2015-11-10 13:56
@fabiopaiva your solution would work only if the options are empty, not when the user search filter makes them empty...+1 for a real solution

**Comment by ErikDubbelboer** [comment] 2015-11-10 14:02
@nadavsinai then you shouldn't use a filter but instead do the filtering in your refresh function.

**Comment by fabiopaiva** [comment] 2015-11-10 14:21
@nadavsinai The real solution is always the best

**Comment by wesleycho** [comment] 2016-03-27 06:33
Closing due to the age of the issue - if this is still a problem, please open a new issue with adequate reproduction in Plunker.

**Closed by wesleycho** 2016-03-27 06:33 UTC
