### ISSUE TITLE
[ui.select:choices] Expected multiple .ui-select-choices-row but got '0'.

### ISSUE THREAD

**Issue by ryanwholey** [angular-ui/ui-select#1355] opened 2015-12-11 20:03 UTC
![screen shot 2015-12-11 at 12 00 07 pm](https://cloud.githubusercontent.com/assets/8100360/11754252/cef2d57e-9ffe-11e5-8111-c10060c2eb82.png)

Error site found at code below

![screen shot 2015-12-11 at 12 02 23 pm](https://cloud.githubusercontent.com/assets/8100360/11754292/2b8bed0c-9fff-11e5-9164-30d1ce3334a7.png)

Created a silly workaround for this issue

````       
        setTimeout(function(){
          var container = $element.querySelectorAll('.ui-select-choices');
          for(var i = 0;  i < 2;  i++) {
            var div = document.createElement('div');
            div.className = 'ui-select-choices-row';
            container[0].children[0].appendChild(div);
          }
        });
````

Thanks!

**Comment by lordnox** [comment] 2016-02-23 11:13
I had the same error. The bug occured in safari when using the mouse only and I did a little more debugging.

The problem I found was with the ng-if added to the choices itself:
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectChoicesDirective.js#L48

The ng-if seems to trigger after the _ensureHighlightVisible is called, which in turn lets the querySelector not find any elements (ng-if removed them from the DOM). After the error is triggered, the elements will be shown as usual, angular will still trigger the ng-if. 
Removing the .attr('ng-if', [...]) removed the bug. I do not know if there are any side effects with this, or if the performance impact is significant enough.

I'd like to have someone else test this, too

**Comment by gatormike** [comment] 2016-02-23 20:47
@lordnox Thanks for the workaround.  I have been using Angular 1.5, and recently started getting the same error, as well as strange performance behavior, as if the browser was processing something and scroll was getting reset.  I commented out the ng-if (added ; on line before as well).   

`choices.attr('ng-repeat', $select.parserResult.repeatExpression(groupByExp));`
`// .attr('ng-if', '$select.open'); //Prevent unnecessary watches when dropdown is close`

Performance is back to normal and I do not see this error anymore.  Thanks!

**Comment by Zelgadis87** [comment] 2016-02-25 22:53
I had the same issue, @gatormike workaround worked for me as a temporary solution.

**Comment by ftorghele** [comment] 2016-03-04 06:29
Me too, removing the .attr('ng-if', [...]) seems to work.

**Comment by Francis54520** [comment] 2016-03-16 09:52
+1 @gatormike  thx.

**Comment by jmblck** [comment] 2016-03-17 15:38
+1

**Comment by pkuklin** [comment] 2016-03-24 09:45
Hey, guys, I have found how to fix this issue without Forking.
I have added attribute(option) : **tagging** to the **ui-select**.
Here is quote from documentation: **If your model is an array of objects, this string is required.**
This worked for me, peace!

**Comment by wesleycho** [comment] 2016-03-28 05:13
Closing as a duplicate of #224

**Closed by wesleycho** 2016-03-28 05:13 UTC

**Comment by devmarwen** [comment] 2016-04-16 10:00
For my case the source of the bug was this:

```javascript
      if (ctrl.$animate && ctrl.$animate.on && ctrl.$animate.enabled(container[0])) {
        ctrl.$animate.on('enter', container[0], function (elem, phase) {
          if (phase === 'close') {
            // Only focus input after the animation has finished
            $timeout(function () {
              ctrl.focusSearchInput(initSearchValue);
              console.log('focusSearchInput()'); // Gets called hunreds of times
            });
          }
        });
```
The `ctrl.focusSearchInput(initSearchValue)` gets called for too many times which will call the      `_ensureHighlightVisible();` accordingly.

Removing the **ngAnimate** module fixes the problem.

**Comment by lsanczyk** [comment] 2016-04-21 18:40
Add the `tagging` attribute binded to a function that return `null`, like this [plunker](http://embed.plnkr.co/WyIC087njDHLmIVGTAj7/), works for me too.

HTML:
`<ui-select ... tagging="tagHandler" ... >`

JS:
```
$scope.tagHandler = function (tag){
    return null;
}
```

**Comment by BVJin** [comment] 2016-10-11 21:56
@lsanczyk Your solution works for me, thank you!

Angular 1.5.0
ui-select 0.14.3

**Comment by deepanshu223** [comment] 2016-11-24 16:48
Thanks @lsanczyk, your solutions saved my day!

**Comment by guoyoujin** [comment] 2017-03-10 01:59
Thanks @lsanczyk Your solution works for me, thank you! Very good
