### ISSUE TITLE
Failed to load template - selectize/select-multiple.tpl.html

### ISSUE THREAD

**Issue by ashubabu** [angular-ui/ui-select#1569] opened 2016-04-21 03:40 UTC
I am trying to use ui-select element with _selectize_ theme and multiple attribute. However, I keep getting the error in loading **selectize/select-multiple.tpl.html**. I had a look at the _select.js_ file in the _dist_ folder here - [https://github.com/angular-ui/ui-select/tree/master/dist](url) and I cannot see the template for select-multiple.tpl.html supported under  _selectize_ theme (**$templateCache.put** only contains _selectize/select.tpl.html_) . 
Is multiple-select not supported under _selectize_ theme yet?

**Comment by user378230** [comment] 2016-04-21 11:22
It is not. Feel free to submit a PR to add support! :smile:

Closing as duplicate of #295

**Closed by user378230** 2016-04-21 11:22 UTC
Labels: duplicate, multiselect, theme:selectize

**Comment by amit-natani** [comment] 2016-06-16 07:24
Which theme is suitable for multi select?

**Comment by user378230** [comment] 2016-06-16 11:28
@amit-natani bootstrap or select2
