### ISSUE TITLE
Delete Bug on Tab

### ISSUE THREAD

**Issue by deadmann** [angular-ui/ui-select#1564] opened 2016-04-18 06:50 UTC
The issues forum is **NOT** for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/ui-select/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.
### Bug description:

My friend write an app, and he has an issue. since i was on git he asked me to ask for the matter.
he has two input box bind with ui-select, and when select of one the item, then he jump to another using tab, he start typing to search something, like a city name, then he say in middle of this matter, i remember something and change my mind, and want to select something else. when he delete all the search letters from search box, after deleting last character, the character return to input box, and get filtered again, say it's impossible to delete whole filter, when you are all keyboard.
### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular:
1.4.9
UI-Select:
0.14.8
Bootstrap/Select2/Selectize CSS (if applicable):

**Comment by user378230** [comment] 2016-04-18 12:33
Hi! 

As requested in the issue template, can you please provide 
>Link to minimally-working plunker that reproduces the issue:

You can use the existing examples here as a start: http://angular-ui.github.io/ui-select/#examples

This will help anyone who investigates this issue see if there is any problem. 

Note also, only the latest version (v0.16.1) is supported.

**Comment by MarcelCremer** [comment] 2016-04-26 14:44
Hey,

I have the same issue as the thread owner but I'm not able to reproduce it in the plunker. Here's at least the structure I have:

http://plnkr.co/edit/XdOGgsSRHznZAks7oMNf?p=preview

Multiple selects inside of an ng-repeat having "dynamically" bound models attached to it.

I've attached you some video where you can see the behaviour. It looks like it has not cleared my previous typed in "o" after I tabbed out. Everytime I click on the control it appears again. After this, I try to delete the letter 3 times and everytime it comes back again.

Hope this might be helpful to anyone....

[failedToDelete.zip](https://github.com/angular-ui/ui-select/files/236831/failedToDelete.zip)

**Comment by darrinholst** [comment] 2016-05-02 14:20
From what I've determined this happens when you initially start typing when the choices are not displayed to activate the select. Then [this line](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L140) kicks in and you can never delete the initial search string that activated it. I'll try to reproduce this in a plunkr.

**Comment by darrinholst** [comment] 2016-05-02 15:20
http://plnkr.co/edit/ADawU4pKDzOQe33xCSHA?p=preview

If you tab into the select from the top input box and start typing you won't be able to ever delete the last character.

**Comment by darrinholst** [comment] 2016-05-02 18:14
Actually this is already fixed in master [here](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L138). We just need a new release cut.

**Comment by MarcelCremer** [comment] 2016-05-03 05:55
That's exactly what I'm experiencing. Nice that you could track it down - I tried to make things too small and forgot the animation Provider...

Thank you Darrin, I'm waiting for the next Release :)

**Comment by eMerzh** [comment] 2016-09-30 19:08
hey, i experienced the issue too, and as @darrinholst said, updating to 19.4 seems to fix my issue ...

so this issue can be closed

**Comment by Jefiozie** [comment] 2016-11-10 08:42
@user378230 , this one can be closed down. See last comment

**Closed** 2016-11-11 07:56 UTC
Labels: needs: investigation, needs: plunkr
