### ISSUE TITLE
ng-model on ui-select does not bind to the actual selected item

### ISSUE THREAD

**Issue by nschejtman** [angular-ui/ui-select#1353] opened 2015-12-11 10:28 UTC
This code is taken from the getting started plunker link:
http://plnkr.co/edit/K9alAMAzvUqCY7Or8RwY?p=preview
```html
<span>Selected: {name: {{selectedItem.name}}, id: {{selectedItem.id}} }</span>
<ui-select ng-model="selectedItem">
  <ui-select-match>
    <span ng-bind="$select.selected.name"></span>
  </ui-select-match>
  <ui-select-choices repeat="item in (itemArray | filter: $select.search) track by item.id">
    <span ng-bind="item.name"></span>
  </ui-select-choices>
</ui-select>
```

This produces the following:
<img width="585" alt="screen shot 2015-12-11 at 11 22 21 am" src="https://cloud.githubusercontent.com/assets/5270246/11741524/f31bdca2-9ff9-11e5-8daf-6d0da9abd0a0.png">

But when changing the selection:
<img width="583" alt="screen shot 2015-12-11 at 11 22 28 am" src="https://cloud.githubusercontent.com/assets/5270246/11741547/0ef3978a-9ffa-11e5-9db4-f641c3967c15.png">
Note that the selectedItem model remains the same regardless of the selection change

**Comment by chrisvel** [comment] 2015-12-11 10:46
+1

**Comment by chrisvel** [comment] 2015-12-11 14:40
This is silly but worked for me :

`$scope.yourmodel = {}; `

You need to initialise an object. 

The 580+ issues in this git repo seem to prove that it's not worth it.

**Comment by justgeek** [comment] 2015-12-16 15:50
+1 also happend to me , but when model was set to an array.

**Comment by yoorek** [comment] 2016-01-08 14:08
This repo has has a design flaw - using inherited scope for reusable  component is very bad:

```uis.directive('uiSelect'
...
  return {
    restrict: 'EA',
    replace: true,
    transclude: true,
    require: ['uiSelect', '^ngModel'],
    scope: true
}
```

This FORCES users to use 'dot' notation. Of course NOT USING dot notation is really bad practice so is "scope: true" which leads to several problems (vide 595 issues).

Just don't use it.

**Comment by user378230** [comment] 2016-01-27 16:33
Duplicate of #1347 

Use 
```html
<ui-select ng-model="selected.item">
```
Where `selected.item` is an property on your controller scope:

```javascript
angular.module('app')
.controller('ctrl', ['$scope', function ($scope){
    $scope.itemArray = [
        ...
    ];

    $scope.selected = { item: $scope.itemArray[0] };
}]);
```

___
Really you should be using controllerAs syntax anyway so you have this:
```html
<ui-select ng-model="ctrl.selectedItem">
```
which should work.

**Comment by Devqon** [comment] 2016-01-29 07:46
@user378230 I agree that controller as syntax is better, but in my case I am creating a wrapper directive around the <ui-select>.

**Comment by user378230** [comment] 2016-01-29 09:37
Maybe I'm misunderstanding, I didn't think such a use case would make much difference, you can use the controllerAs syntax with directives too. 

A plunkr might be useful if its not working :)

**Comment by wesleycho** [comment] 2016-03-28 05:12
Closing as a usage issue. This is a question better suited for a place like StackOverflow.

**Closed by wesleycho** 2016-03-28 05:12 UTC

**Comment by yaoelvon** [comment] 2016-05-30 12:34
thanks, this helps me!

**Comment by iridiumsoft** [comment] 2018-02-03 11:01
In my case i had to make ng-model an object and initialize it. `$scope.data = {}` and then in `ui-select` `ng-model="data.model_name"`
