### ISSUE TITLE
Doesn't work with fancybox.

### ISSUE THREAD

**Issue by Perpherior** [angular-ui/ui-select#376] opened 2014-11-05 14:23 UTC
Display error
```
Illegal use of ngTransclude directive in the template!
```
I had used ui-select in multi places, and they work fantastically well.  
Now I'm trying to use it in a popup fancybox  page, which is trigger by calendar. It directly displays the error above. I could understand this is because of transclude. But really new to angular js, this problem gets me. Does anyone meet the similar issue? Could someone show me some suggestion? 
Very appreciate

**Comment by wesleycho** [comment] 2016-03-27 15:22
Closing due to lack of reproduction - feel free to open a new issue with appropriate reproduction in Plunker based on the latest release if this is still an issue.

**Closed by wesleycho** 2016-03-27 15:22 UTC
