### ISSUE TITLE
Clearing options with selected value

### ISSUE THREAD

**Issue by amcdnl** [angular-ui/ui-select#338] opened 2014-10-23 15:06 UTC
I have a scenario where I need to update the values on each 'changed' from another control.  I wipe out all the values and apply the new applicable values for that given change value.  

If I have a selected value that is selected and available before AND after the update, the display box is correct but the value is not highlighted in the dropdown despite still showing selected.

In this screenshot, you can see the selected value in the top but the value not showing highlight in the dropdown.  http://www.screencast.com/t/PF8ZrQpI

The solution is probably re-highlight values on dropdown?

**Comment by wesleycho** [comment] 2016-03-27 07:10
Closing due to age of issue - feel free to open a new issue with reproduction based on the latest release if this is still an issue.

**Closed by wesleycho** 2016-03-27 07:10 UTC
