### ISSUE TITLE
Choices not contain value that same with initial ng-model value

### ISSUE THREAD

**Issue by DmitryKrekota** [angular-ui/ui-select#1660] opened 2016-06-14 10:04 UTC
### Bug description:
Choices not contain value that same with initial ng-model value

### Link to zip-file that contain the issue:
https://drive.google.com/file/d/0Bxtv10NlSOEbR3I5UWZPZDVvSFE/view?usp=sharing

### Link to screen record that contain the issue:
https://drive.google.com/file/d/0Bxtv10NlSOEbODhXNkJVZ18wem8/view?usp=sharing

### Version of Angular
1.5.0

### UI-Select
0.17.1

**Comment by RUDIWER** [comment] 2016-06-14 12:51
Hello,

I have the same probblem !! Do you already have a solution ???

**Comment by DmitryKrekota** [comment] 2016-06-14 12:58
I have solution to use $timeout, but this workaround is bad..

```
angular.module('app', ['ngSanitize', 'ui.select'])
    .controller('AppController', [
        '$scope',
        '$timeout',
        function($scope, $timeout) {
            $timeout(function(){
                $scope.selcectedSpacing = 'auto';
            });
            $scope.spacings = ['zero', 'auto', 'small', 'medium', 'large'];
        }
    ]);
```

**Comment by user378230** [comment] 2016-06-15 10:19
Can you please describe the problem in text as well through screen recording? (Reproduction steps, expectations etc.) For those who are not able to view the video.

**Comment by willisd3** [comment] 2016-06-15 19:09
demonstrating the fact that the list of ui-select-choices will not include the one that matches the initial value of the ng-model: [Plunkr](http://plnkr.co/edit/kEw0l3)

**Comment by willisd3** [comment] 2016-06-15 19:49
Ok, more info.

Explicitly setting the remove-selected attribute to "false" on the <ui-select> element will prevent the initial ng-model value from being removed from the collection of choices, regardless of whether the 'multiple' attribute is set on <ui-select>. Whatever logic is being invoked to remove selected items from the collection of choices should probably check whether the multiple attribute is present as well as the state of the remove-selected attribute.

**Comment by DmitryKrekota** [comment] 2016-06-16 07:57
willisd3, thanks for your info. With remove-selected="false" everything works fine for me.
```
<ui-select ng-model="selcectedSpacing" remove-selected="false">
    <ui-select-match><span>{{ selcectedSpacing }}</span></ui-select-match>
    <ui-select-choices repeat="spacing in spacings track by $index"><span>{{ spacing }}</span></ui-select-choices>
</ui-select>
```

**Comment by jeroenbreen** [comment] 2016-06-19 21:05
I noticed that in 0.16.0 this was working properly. `remove-selected` works for me.

**Comment by JCherryhomes** [comment] 2016-07-05 22:08
Another issue related to this occurs when you press the 'Enter' key to make your selection. If you use your mouse to make selections after making a selection using the 'Enter' key you will notice that the item selected using the 'Enter' key remains hidden until you make another selection using the 'Enter' key.

The remove-selected attribute fixes this as well.

**Comment by user378230** [comment] 2016-07-11 13:41
Closing as duplicate of #1654

**Closed by user378230** 2016-07-11 13:41 UTC
Labels: needs: info, needs: plunkr

**Comment by muni510** [comment] 2017-05-30 16:29
add  remove-selected="false" option to ui-select directive

`<ui-select ng-model="ctrl.person.selected" theme="bootstrap" remove-selected="false">`
