### ISSUE TITLE
Clear button shown on disabled select

### ISSUE THREAD

**Issue by michalmatovcik** [angular-ui/ui-select#980] opened 2015-06-02 08:40 UTC
I have ui-select with ng-disabled =false.
Select itself behave as expected - so i cannot select another value.

But clear  button (allow-clear=true) is still shown and working!

Suggestion:
I have fixed it in my own app - by changing setAllowClear function to set $select.allowClear to false if $select.disabled is true.

Next step is to call setAllowClear function from inside of $select.disabled watcher.

Please evaluate this bug and fix it.
thanks

**Comment by blowsie** [comment] 2015-06-08 11:01
For me the clear button does not show when the input is disabled

**Comment by michalmatovcik** [comment] 2015-06-15 05:12
which version are you using? i have found it in latest release

2015-06-08 13:01 GMT+02:00 Sam Blowes <notifications@github.com>:

**Comment by wesleycho** [comment] 2016-03-27 22:40
Closing due to lack of reproduction in Plunker - feel free to open a new issue with a Plunker if it is still a problem.

**Closed by wesleycho** 2016-03-27 22:40 UTC
