### ISSUE TITLE
Input on multi-select is not being calculated properly, being pushed underneath the last selection

### ISSUE THREAD

**Issue by JGailor** [angular-ui/ui-select#342] opened 2014-10-24 23:35 UTC
http://d.pr/i/1kTv9

**Comment by wesleycho** [comment] 2016-03-27 07:12
Closing due to link (only description) being broken.

Feel free to open a more detailed issue with proper reproduction in Plunker based on the latest release if it is still an issue.

**Closed by wesleycho** 2016-03-27 07:12 UTC
