### ISSUE TITLE
Programatically focus the select (but not activate)

### ISSUE THREAD

**Issue by pietschy** [angular-ui/ui-select#201] opened 2014-09-18 23:31 UTC
Hi there,

I'm trying to figure out the the best way to focus the select when my page is displayed.  In hunting around there's a uiSelectCtrl.activate() method but no equivalent for focus.  In digging around HTML5 has an autofocus attribute but wasn't if that would make sense in SPAs or provide much value over a programatic focus mechanism. 

I'm happy to do a pull request, but given I'm fairly new to angular, do you have any suggestions for approaching this?

Thanks!

**Comment by MWalid** [comment] 2015-01-05 11:53
@adharris You saved my day... thanks :+1:

**Comment by kimardenmiller** [comment] 2015-01-08 03:33
@adharris, just for clarity, when you further add the ```uiSelectWrapper```, what do you do with the ```<the ui select DOM element>``` line to match that?  That's where you want to get a reference to the uiSelect dom element as required by your first post?

**Comment by kimardenmiller** [comment] 2015-01-16 21:55
I guess @surabhi-batra and @MWalid got this working? User the wrapper:
```Slim
.form-group ng-controller='HubController' 
    div(ui-select-wrapper)
      ui-select class='vote_hub' ng-disabled='disabled' ng-model='hubFilter.selected' on-select='setHub($item, $model); finishProp()' reset-search-input='false'
        ui-select-match id='vote_hub' placeholder='Who should see your proposal? ...' ng-enter='finishProp()' {{$select.selected.full_hub}}
        ui-select-choices refresh='refreshHubs($select.search)' refresh-delay='0' repeat='hub in hubs track by $index'
          div ng-bind-html='hub.full_hub | highlight: $select.search'
```

For some reason both those console.logs come up undefined:  ```.controller('uiSelect')``` at the directive level:
```CoffeeScript
uiSelectWrapper = ->
  link: (scope, element, attrs) ->
    uiSelectController = element.children().controller('uiSelect')
    console.log 'uiSelectController: ', uiSelectController
    uiSelectController
```

and focusser[0] at the controller level:
```CoffeeScript
  uiSelect = angular.element 'ui-select-wrapper'
  console.log 'uiSelect: ', uiSelect.focusser[0]
```

Suggestions?

**Comment by rogier21** [comment] 2015-02-03 18:21
When opening the select list with Activate the focus won't be put on the searchbox, is this a bug or expected behavior?

**Comment by kimardenmiller** [comment] 2015-02-04 02:09
@rogier21 , you were able to get a hold of the controller then using the wrapper above?

**Comment by rogier21** [comment] 2015-02-04 02:11
@kimardenmiller yeah, the code works, I did exactly as adharris commented on Dec 11, 2014. But it doesn't focus the search after opening.

**Comment by kimardenmiller** [comment] 2015-02-04 02:13
You trid ```uiSelect.focusser[0].focus()```?  

What version are you on?

**Comment by rogier21** [comment] 2015-02-04 14:11
Latest release: Version: 0.9.6 - 2015-01-12T20:24:40.589Z

**Comment by stefan--** [comment] 2015-02-05 10:20
@kimardenmiller cannot get hold of the 'uiSelect' controller neither. Have you been able to solve it?

**Comment by kimardenmiller** [comment] 2015-02-05 17:39
@stefan-- I have not yet solved it. 

@rogier21 I'm also on v. 0.9.6., but like stefan, cannot find the controller functions described by @adharris.

console.logs come up undefined for: ```.controller('uiSelect')``` for the wrapper as configured above.

You were able to hit the controller off the wrapper to open, so ```uiSelect.activate()``` works for  you?

**Comment by rogier21** [comment] 2015-02-05 23:28
@kimardenmiller are you asking me?

I just do this:

	var selectElement = container.find('.ui-select-container');
	var uiSelect = selectElement.controller('uiSelect');
	uiSelect.open = true;
	uiSelect.activate(false, true);

And it pops open the dropdown list... `uiSelect` contains the controller if I do a console.log on it I see all the properties I would expect.

**Comment by kimardenmiller** [comment] 2015-02-06 03:12
Interesting @rogier21. Seems you are not using the 'wrapper' idea then, correct?  Seems to yield a little closer results for me, but still no actual focus happening.

Outputting uiSelect.focusser[0] to the console I now get the input element:

```<input ng-disabled="$select.disabled" class="ui-select-focusser ui-select-offscreen ng-scope" type="text" aria-haspopup="true" role="button">```

And ```uiSelect2.focusser[0].focus()``` runs, but does not do anything. I did my selections slightly differently, as container.find did not seem to work in my case, so I did:
```Coffeescript
    selectElement = angular.element('.ui-select-container')
    uiSelect = selectElement.controller('uiSelect')

**Comment by kimardenmiller** [comment] 2015-02-06 17:55
Experimenting more, I found that the following will focus the ui-select, but only after an additional keystroke at the keyboard:
```coffeescript
    $timeout ->
      element = angular.element '.ui-select-focusser'
      element.focus()  if element
```
Before this code runs, the previous field has focus:
![image](https://cloud.githubusercontent.com/assets/2165336/6084415/b310a914-ade5-11e4-8d01-cc08d3048569.png)
When the above code runs, you can see that field losing focus:
![image](https://cloud.githubusercontent.com/assets/2165336/6084395/7d3332e4-ade5-11e4-9bc7-9451faf30bab.png)
But only after (any) keystroke do does ui-Select gain focus:
![image](https://cloud.githubusercontent.com/assets/2165336/6084433/e49b00ba-ade5-11e4-8a98-41f4b205309b.png)

Thoughts on what else needs to be done fully gain focus of the ui-select input?

**Comment by timmyrosen** [comment] 2015-02-09 21:33
I went with the wrapper directive approach and hade the same problem with the input not being focused, but got it working by adding a timeout to the active()-method.

Like this:
```javascript
    link: function(scope, element, attrs) {
            var uiSelectController = element.children().controller('uiSelect');
            console.log(uiSelectController);
            $timeout(function() {
                uiSelectController.activate(false, true);
            }, 50);
        }

**Comment by kimardenmiller** [comment] 2015-02-09 22:19
@timmyrosen does your ```console.log(uiSelectController);``` produce the controller or _undefined_?

Mine produces _undefined_. 

Can you see your html?

**Comment by timmyrosen** [comment] 2015-02-09 22:40
@kimardenmiller My console.log gives me the controller, otherwise it wouldn't work.

Sure, here is my html:
```html
    <ui-select-wrapper focus="true">
      <ui-select ng-model="prompt.selected" on-select="prompt.onSelect($item)">
        <ui-select-match placeholder="Sök användare">{{$select.selected.given_name || $select.selected}}</ui-select-match>
        <ui-select-choices repeat="user as user in prompt.users | filter: $select.search">
          <div ng-bind-html="user.given_name + ' ' + user.last_name | highlight: $select.search"></div>
        </ui-select-choices>
      </ui-select>
    </ui-select-wrapper>
```

Full directive:
```javascript
  app.directive('uiSelectWrapper', function($timeout) {
    return {
        restrict: 'AE',
        scope: {
            focus: '='
        },
        link: function(scope, element, attrs) {
            var uiSelectController = element.children().controller('uiSelect');
            if (scope.focus) {
                $timeout(function() {
                    uiSelectController.activate(false, true);
                }, 50);
            }
        }
    };
});

**Comment by kimardenmiller** [comment] 2015-02-09 23:03
@timmyrosen Thank you. My controller comes back undefined and I don't know why.

Cut and pasted your code in and get ```TypeError: Cannot read property 'activate' of undefined```

What version of Angular are you on?

**Comment by kimardenmiller** [comment] 2015-02-09 23:22
My html is authored in Slim, then renders like so:
```html
<div ui-select-wrapper="">
  <div class="vote_hub ui-select-container ui-select-bootstrap dropdown ng-pristine ng-invalid ng-invalid-required" ng-class="{open: $select.open}" name="hubFilter" ng-disabled="disabled" ng-model="sessionSettings.hubFilter" on-select="setHub($item, $model); finishProp()" required="required" reset-search-input="false">
    <div class="btn-group ui-select-match btn-block" ng-hide="$select.open" ng-disabled="$select.disabled" ng-class="{'btn-default-focus':$select.focus}" id="vote_hub" ng-enter="finishProp()" placeholder="Who should see your proposal? ...">
      <button type="button" class="btn btn-default col-sm-10 col-md-11" ng-class="{'col-sm-8 col-md-10': $select.allowClear &amp;&amp; !$select.isEmpty(),'col-sm-10 col-md-11': !$select.allowClear || $select.isEmpty()}" tabindex="-1" ;="" ng-click="$select.activate()">
        <span ng-show="$select.isEmpty()" class="text-muted ng-binding">Who should see your proposal? ...</span> 
      <span ng-hide="$select.isEmpty()" ng-transclude="" class="ng-hide"><span class="fa fa-search ng-scope">&nbsp;</span><span class="ng-binding ng-scope"></span><span class="close ng-scope" ng-click="clear($event)">×</span></span></button> <!-- ngIf: $select.allowClear && !$select.isEmpty() --> 
    <button class="btn btn-default col-sm-2 col-md-1" ng-click="$select.activate()"><span class="caret ui-select-toggle" ng-click="$select.toggle($event)"></span></button></div><input type="text" autocomplete="off" tabindex="-1" class="form-control ui-select-search ng-pristine ng-valid ng-hide" placeholder="Who should see your proposal? ..." ng-model="$select.search" ng-show="$select.searchEnabled &amp;&amp; $select.open">
  <ul class="ui-select-choices ui-select-choices-content dropdown-menu ng-scope ng-hide" role="menu" aria-labelledby="dLabel" ng-show="$select.items.length > 0" refresh="refreshHubs($select.search)" refresh-delay="0" repeat="hub in hubs track by $index"><li class="ui-select-choices-group"><div class="divider ng-hide" ng-show="$select.isGrouped &amp;&amp; $index > 0"></div><div ng-show="$select.isGrouped" class="ui-select-choices-group-label dropdown-header ng-binding ng-hide" ng-bind-html="$group.name"></div><!-- ngRepeat: hub in $select.items track by $index --></li></ul><input ng-disabled="$select.disabled" class="ui-select-focusser ui-select-offscreen ng-scope" type="text" aria-haspopup="true" role="button"></div></div>
```

**Comment by timmyrosen** [comment] 2015-02-10 09:58
@kimardenmiller Wow, that's really messy, but looking at the first element in the wrapper it should work really. I'm on Angular v 1.3.11. What does your directive look like?

**Comment by kimardenmiller** [comment] 2015-02-10 22:07
@timmyrosen keep in mind, I took compiled code from the dom to show you. My actual code (Slim) is:
```Slim
    div(ui-select-wrapper)
       ui-select( name='hubFilter' class='vote_hub'
            ng-disabled='disabled' ng-model='sessionSettings.hubFilter'
            on-select='setHub($item, $model); finishProp()'
            reset-search-input='false' required )
          ui-select-match id='vote_hub' placeholder='{{ sessionSettings.actions.hubPlaceholder }}' ng-enter='finishProp()'
            span class='fa fa-search' &nbsp
            span {{ $select.selected.full_hub }}
            span class='close' ng-click='clear($event)' &times
          ui-select-choices refresh='refreshHubs($select.search)' refresh-delay='0' repeat='hub in hubs track by $index'
            div ng-bind-html='hub.full_hub | highlight: $select.search'
```
I showed you compiled code in case compilation is my problem.
My directive is a cut and paste of yours (ported to CoffeeScript):
```Coffeescript
uiSelectWrapper = ($timeout) ->
  restrict: "AE"
  scope:
    focus: "="

  link: (scope, element, attrs) ->
    uiSelectController = element.children().controller("uiSelect")
    console.log 'uiSelectController Rosen: ', uiSelectController
    if scope.focus
      $timeout (->
        uiSelectController.activate false, true
      ), 50
```
I'm on Angular 1.9, before the big changes. So I guess it could be there.

**Comment by timmyrosen** [comment] 2015-02-11 11:39
@kimardenmiller Angular 1.9? Do you mean 1.2.9? If so, then yeah that may be the case. If you can, I would recommend that you update to at least 1.3.

If you look at my directive you can see that I have a focus-attribute which must be set to true on the element (ui-select-wrapper) for the focus to take effect. Although if you still get undefined on the controller object, then the focus attribute doesn't really matter, and I would guess it may have something to do with the older version of angular.

**Comment by kimardenmiller** [comment] 2015-02-11 22:07
Yes, @timmyrosen. Thanks for the careful eye on that. I actually did remove that if statement in the one I'm running:
```coffeescript
uiSelectWrapper = ($timeout) ->
  link: (scope, element, attrs) ->
    uiSelectController = element.children().controller('uiSelect')
    console.log 'uiSelectWrapper Directive Log: ', uiSelectController
    $timeout ->
      uiSelectController
      console.log 'uiSelectWrapper Directive Log: ', uiSelectController
    , 550
```
So nothing on either console.log

I'll upgrade to ng 1.3 and see what it looks like then. Thanks so much for the time!

BTW: Went to see a preview of ng 2.0 last night in Mountain View. Crazy amount of changes actually. But exciting stuff. Start thinking ES6!

**Comment by dimirc** [comment] 2015-03-07 05:09
Take a loot at https://github.com/angular-ui/ui-select/pull/728 and let me know your comments on the PR pls

**Comment by kimardenmiller** [comment] 2015-03-09 00:12
@dimirc the functionality looks awesome :+1: 

So it was really as simple as this line in the link function?:  
```$select.setFocus(); ```

All the need for this extra wrapper to _"focus the focuser"_ was never necessary?

Is the magic that this line is _in the link fuction_ as opposed to trying to hit the focuser from demo.js?

**Comment by dimirc** [comment] 2015-03-09 00:37
@kimardenmiller keep in mind that [setFocus()](https://github.com/angular-ui/ui-select/pull/728/files#diff-abde4a481e0d1eb6531858ade35f95abR312) is just added with this PR

**Comment by dimirc** [comment] 2015-03-09 00:38
https://github.com/angular-ui/ui-select/pull/728 merged

**Closed by dimirc** 2015-03-09 00:38 UTC

**Comment by konrness** [comment] 2015-04-14 03:49
@kimardenmiller did you ever find the cause of your uiSelectController being undefined as of your Feb 11 comment? I'm having the same problem.

**Comment by kimardenmiller** [comment] 2015-04-14 05:13
I didn’t, but the new focus feature (undocumented?) does seem to work.

/k

**Comment by ericbolo** [comment] 2015-05-17 15:45
I had the same problem with uiSelectController being undefined. The problem is that at the time that the link function in my wrapper directive executes, the controller has not yet been added. Setting a long enough timeout (here, 5 seconds to make sure) "solved" it:

$timeout(function () {
                    var selectElement = angular.element('.ui-select-container')
                    var uiSelect = selectElement.controller('uiSelect')
                    console.log("controller", uiSelect)
                }, 5000)

Obviously a hack. Any event I could use to figure out when the controller has been initialized?

**Comment by jb41997** [comment] 2015-06-03 17:10
Quick question.
I have ui-select working great, but I'm trying to prevent the keyboard from popping on mobile devices when the dropdown is selected.  I'm having a hard time grasping exactly how this is achieved using the methods outlined above.  What is the best way to handle this considering the new setFocus() functionality etc.?  A quick explanation from start to fin would be greatly appreciated for us noobs!

**Comment by mbcooper** [comment] 2015-08-31 22:03
This all seems very hacky.  Could we not add a one-time flag to the attributes that we can change to get a focus?
