### ISSUE TITLE
ui-select unflags FormController's $pristine state

### ISSUE THREAD

**Issue by reifi** [angular-ui/ui-select#341] opened 2014-10-24 11:40 UTC
$watcher on $select.selected will $setViewValue() which will unflag $pristine and set $dirty, allthough it's the initial $watcher and there is no preselection.

https://github.com/angular-ui/ui-select/blob/master/src/select.js#L771

This would fix it:
<pre>
scope.$watchCollection('$select.selected', function(newCol) {
            if (ngModel.$pristine && newCol.length === 0)  {
              // preserve $pristine state for empty values, don't setViewValue
            } else {
              ngModel.$setViewValue(Date.now()); //Set timestamp as a unique string to force changes
            }
</pre>

**Comment by kether667** [comment] 2015-03-13 18:58
+1

**Comment by kether667** [comment] 2015-03-13 18:59
duplicate of #289

**Comment by KevinPHughes** [comment] 2015-03-13 20:40
I don't think this is a duplicate of 289, that one has been incorporated into the latest version and I'm still seeing an issue.

If you load the 'options' or the ng-model value asynchronously the form will always be dirty: 

http://plnkr.co/edit/Iv1H4T5OYkLr1uevTe6g?p=preview

**Comment by kether667** [comment] 2015-03-13 20:46
There's no fixes in 289 in master yet and it's the same issue, form is always dirty

**Comment by cmlenz** [comment] 2015-03-25 15:37
#289 was fixed via #509. This issue should be closed, too.

**Comment by gerardp** [comment] 2015-07-02 10:31
I have the same problem.
My form is always dirty !

**Comment by benri** [comment] 2015-08-28 21:08
For those who need a quick fix, manually put 'ng-pristine' class in the html, then when something is selected it'll go away

**Comment by wesleycho** [comment] 2016-03-27 07:11
Closing as fixed - if this is still an issue, feel free to open a new issue with reproduction based on the latest release.

**Closed by wesleycho** 2016-03-27 07:11 UTC

**Comment by samuelcastro** [comment] 2016-10-22 03:04
Same issue here using `"ui-select": "~0.19.4"`
