### ISSUE TITLE
ngRepeat:dupes error for multi select and remote data source

### ISSUE THREAD

**Issue by yannlebel** [angular-ui/ui-select#781] opened 2015-03-19 19:02 UTC
Hi,

I found a race condition in the latest version v0.11.2, for multi select.

If the data source of the select is loaded after the selection the widget raise the error ngRepeat:dupes and create duplicates item in the drop down.
But if the data source is loaded before the selection everything works as expected.

Here is a plunker to demonstrate the issue [http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview]

In this plunker if the variable objectLoadTime (line 6) is lower than dataSourceLoadTime (line 5) everything works

If the variable objectLoadTime is greater than dataSourceLoadTime duplicates are created.

Thanks

**Comment by benno208** [comment] 2015-05-04 15:07
+1

**Comment by savokiss** [comment] 2016-01-19 09:10
+1， I cant find the demo code. But as you say, I prepare the data before ui-select render and it works!

**Comment by mauricioborges** [comment] 2016-03-09 22:28
+1. Has anyone found a workaround?

**Comment by wesleycho** [comment] 2016-03-27 20:58
Closing as a duplicate of several ng-repeat errors.

**Closed by wesleycho** 2016-03-27 20:58 UTC
