### ISSUE TITLE
How to validate the select input?

### ISSUE THREAD

**Issue by burzum** [angular-ui/ui-select#788] opened 2015-03-23 12:24 UTC
I've already spent some time on trying to figure out how to do this without much success:

How can I validate an input to be not empty using the standard angular form validation mechanism?

**Comment by Sylox** [comment] 2015-04-09 10:34
+1

**Comment by JobaDiniz** [comment] 2015-04-24 19:28
+1.

I've tried to change the code to also pass `name`parameter, however nothing worked:
Angular 1.2.28

**select template**
```
<div class="ui-select-container ui-select-bootstrap dropdown" ng-class="{open: $select.open}">
    <div class="ui-select-match"></div>
    <input type="text" autocomplete="off" tabindex="-1" id="{{$select.id}}" name="{{$select.name}}"
           aria-expanded="true"
           aria-label="{{ $select.baseTitle }}"
           aria-owns="ui-select-choices-{{ $select.generatedId }}"
           aria-activedescendant="ui-select-choices-row-{{ $select.generatedId }}-{{ $select.activeIndex }}"
           class="ui-select-search"
           placeholder="{{$select.placeholder}}"
           ng-model="$select.search"
           ng-show="$select.searchEnabled && $select.open">
    <div class="ui-select-choices"></div>
</div>

```
**uiSelectMatch**
```
directive('uiSelectMatch', ['uiSelectConfig', function(uiSelectConfig) {
            return {
                restrict: 'EA',
                require: '^uiSelect',
                replace: true,
                transclude: true,
                templateUrl: function(tElement) {
                    // Gets theme attribute from parent (ui-select)
                    var theme = tElement.parent().attr('theme') || uiSelectConfig.theme;
                    var multi = tElement.parent().attr('multiple');
                    return theme + (multi ? '/match-multiple.tpl.html' : '/match.tpl.html');
                },
                link: function(scope, element, attrs, $select) {
                    $select.lockChoiceExpression = attrs.uiLockChoice;
                    attrs.$observe('placeholder', function(placeholder) {
                        $select.placeholder = placeholder !== undefined ? placeholder : uiSelectConfig.placeholder;
                    });
                    attrs.$observe('name', function(name) {
                        $select.name = name !== undefined ? name : uiSelectConfig.name;
                    });
                    attrs.$observe('id', function(id) {
                        $select.id = id !== undefined ? id : uiSelectConfig.id;
                    });

                    $select.allowClear = (angular.isDefined(attrs.allowClear)) ? (attrs.allowClear === '') ? true : (attrs.allowClear.toLowerCase() === 'true') : false;

                    if($select.multiple){
                        $select.sizeSearchInput();
                    }

                }
            };
        }])
```

*Related issues: https://github.com/angular-ui/ui-select/issues/556 https://github.com/angular-ui/ui-select/issues/850 https://github.com/angular-ui/ui-select/issues/354*

**Comment by Josh68** [comment] 2015-05-01 17:23
I recently worked on a small typeahead directive in my own project. This seems to have worked.

(Idea taken from https://gist.github.com/mbenford/dd7556f01963f49e5c7d (mbenford))

Implement another directive for binding attributes (sort of a replacement for ngAttr)

```
angular.module('ngApp')
    .directive('ngBindAttrs', ['$parse', ngBindAttrsDirective]);

  function ngBindAttrsDirective($parse) {
    return {
      restrict: 'A',
      controller: function($scope, $element, $attrs) {
        var attrsObj = $scope.$eval($attrs.ngBindAttrs);
        angular.forEach(attrsObj, function(value, key) {
          $attrs.$set(key, value);
        });
      }
    };
  }
```
Pass it to the select's (or whatever other directive's) isolated scope:
```
<element input-name="inputValue"></element>
```
```
scope: {
    inputName: '@'
}
```
Use it like this in the select input's (or other directive's) template:
```
ng-bind-attrs="{name: inputName}"
```
My template's input now registers with the form controller correctly and sets up all of the appropriate angular validation properties and methods on itself and the form.

**Comment by ibbatta** [comment] 2015-06-08 10:46
+1

**Comment by talski** [comment] 2015-08-11 12:50
+1

**Comment by crearc** [comment] 2015-08-11 22:40
+1

**Comment by jingzhou123** [comment] 2015-09-24 04:01
+1

**Comment by netrevisanto** [comment] 2015-10-23 20:33
+1

**Comment by ibbatta** [comment] 2015-10-26 11:35
+1

**Comment by keithmullins** [comment] 2016-01-14 20:00
+1

**Comment by rosscdh** [comment] 2016-01-20 13:25
+1

**Comment by ibbatta** [comment] 2016-01-20 15:43
+1

**Comment by AlexEmashev** [comment] 2016-02-18 12:13
same problem

**Comment by lpotapczuk** [comment] 2016-03-02 08:11
+1

**Comment by devmarwen** [comment] 2016-03-23 19:39
:+1:

**Comment by wesleycho** [comment] 2016-03-27 17:14
Closing as a duplicate of #403 at heart

**Closed by wesleycho** 2016-03-27 17:14 UTC
