### ISSUE TITLE
ui-select choices cannot scroll in ion-view and ion-modal-view. Can only scroll in ionicPopup

### ISSUE THREAD

**Issue by boyfunky** [angular-ui/ui-select#1330] opened 2015-11-28 06:20 UTC
So i have a form that has a ui-select. And then it populates the data, the list of the options cannot scroll. It can only scroll if it is ionicPopup. But with ionicView and ionicModal, it refuses to scroll.

**Comment by humaknight** [comment] 2015-12-10 16:53
I have the same problem :(

I and looking for a solution...

**Comment by humaknight** [comment] 2015-12-11 09:39
I detect this:

When input text have focus you can not scroll with touch in the list.

If the input text lose focus you can scroll but you can not filter list with some text

**Comment by boyfunky** [comment] 2015-12-11 10:17
i ended up not using angular ui-select. I am using ion-autocomplete. u could give it a try. anythg u can ask me if u hv problems

**Comment by humaknight** [comment] 2015-12-11 10:43
Thanks a lot.

It´s very interesting.

Regards

**Comment by wesleycho** [comment] 2016-03-28 04:58
Closing due to lack of reproduction

**Closed by wesleycho** 2016-03-28 04:58 UTC

**Comment by mnewmedia** [comment] 2016-11-07 10:16
This is because ionic uses default and globally native scrolling. You can switch back to js scrollin when you add overflow-scroll="true" to your ion-content.
```html
overflow-scroll="true"
```

**Comment by shuwan9** [comment] 2018-09-06 12:22
@mnewmedia it works for me,thanks a lot.
