### ISSUE TITLE
TemplateCache on first load

### ISSUE THREAD

**Issue by tomaszwilk** [angular-ui/ui-select#1345] opened 2015-12-07 14:57 UTC
Hi,
I have a problem using  <ui-select>. Directive is trying to fetch templates using http request always ignoring templateCache on first access and giving 404. Try browsing in private mode and open page with ui-select. First time I access it I get http requests for templates with 404 (bootstrap/match.tpl.html, bootstrap/choices.tpl.html, bootstrap/select.tpl.html) than when I refresh its ok. Content with ui-select is loaded using ngRoute inside a tab.

Similar behavior was reported by @hoetmaaiers in #992

**Comment by wesleycho** [comment] 2016-03-28 05:01
Closing due to lack of reproduction - feel free to open a new issue with reproduction in Plunker, although I believe this is a support issue.

**Closed by wesleycho** 2016-03-28 05:01 UTC
