### ISSUE TITLE
Multi-Search is not re-sized when it becomes enabled

### ISSUE THREAD

**Issue by schaliasos** [angular-ui/ui-select#381] opened 2014-11-06 14:08 UTC
Hi,
I have a weird case where the multi-search control is initially disabled with some values. When it becomes enabled, the size of the inner input control is not recalculated. That has as a result, its width to be greater than the available.

Check here: http://plnkr.co/edit/Hqltb7F9g4pMJOBI5ZWf?p=preview

Enable the control and see what happens.

**Comment by wesleycho** [comment] 2016-03-27 15:25
Closing as duplicate of ##379.

**Closed by wesleycho** 2016-03-27 15:25 UTC
