### ISSUE TITLE
group-by not working on ALL IE 

### ISSUE THREAD

**Issue by Matul87** [angular-ui/ui-select#370] opened 2014-11-04 10:57 UTC
Hi,

When I used ui-select on IE, I watched that **group-by option not working all versions of Internet Exprlorer**. Below are screenshoots from demo **ui-select** page called **'demo-groupby.html'** .

**INTERNET EXPLORER EXAMPLE - NOT WORKING:**
![ie](https://cloud.githubusercontent.com/assets/9047284/4898406/2d3dc91c-6410-11e4-9e4b-ecca4fc95f3d.png)

**GOOGLE CHROME EXAMPLE - ALL OK:**
![chrome](https://cloud.githubusercontent.com/assets/9047284/4898523/5604db8c-6411-11e4-96a3-9da5ad4d1e9d.png)

**Comment by Matul87** [comment] 2015-01-09 14:47
Anybody fixes this bug?

**Comment by ariovistus** [comment] 2015-02-09 20:44
in release 0.9.4, the error thrown observed by the OP is replaced with

Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context.

using IE 10 and angular 1.2.25

**Comment by amcdnl** [comment] 2015-02-10 13:03
@ariovistus can you create a example plunker?

**Comment by wesleycho** [comment] 2016-03-27 15:20
Closing due to age - feel free to open a new issue with reproduction based on the latest release if it is still a problem.

**Closed by wesleycho** 2016-03-27 15:20 UTC
