### ISSUE TITLE
$select.selected is not updated when a new value pushed to ng-model

### ISSUE THREAD

**Issue by mkeremguc** [angular-ui/ui-select#560] opened 2015-01-03 05:54 UTC
long story short, i have some async calls to api to get the ng-model initialized/updated accordingly. However, it doesn't update view of a multiple select right after..
i "sometimes" get some throw: "Error: [ui.select:multiarr] Expected model value to be array but got '5'"
altho it shouldn't be the case since the ng-model doesn't get updated from user input at that time but i suspect some race conditions between ngmodel->view and view->ngmodel

here is a simple plunker forked from the example:
http://plnkr.co/edit/mhQW9aCjoAir1DzVMPUk?p=preview
just a timeout push to multipleDemo.colors, there you see the ngmodel gets updated but select input is not..
no problem for non-multiple selects..

**Comment by tjdavenport** [comment] 2015-01-13 16:41
I'm also having this issue

**Comment by Flightfreak** [comment] 2015-01-15 14:44
Is it not related to this issue? https://github.com/angular-ui/ui-select/issues/404 Fix might be soon available. https://github.com/angular-ui/ui-select/pull/256

**Comment by MBentley1976** [comment] 2015-01-27 22:00
I have this issue as well

**Comment by jukkasi** [comment] 2015-01-31 00:46
Probably something I'm seeing too, commented in #256 

PR fix does not affect plnkr example since no tracked by is used, though I think this is something that should work out of the box

**Comment by mkeremguc** [comment] 2015-02-08 17:34
this seems fixed. however, if you want to push to match externally, you need to push to your choices first

**Comment by wesleycho** [comment] 2016-03-27 17:17
Closing as fixed as per comments - feel free to open a new issue with appropriate reproduction if this is still an issue.

**Closed by wesleycho** 2016-03-27 17:17 UTC
