### ISSUE TITLE
Tagging in single selection does not work when clicking a different field

### ISSUE THREAD

**Issue by ps3331333** [angular-ui/ui-select#1748] opened 2016-08-01 12:05 UTC
In this plunk I have two elements, a ui-select with tagging enabled and an input field. If I enter a value not in the list in ui-select AND then click on the field, ui-select loses its value

[PLUNK](http://plnkr.co/edit/36IRP9J079vjWFIFjRSb?p=preview)

**Comment by Jefiozie** [comment] 2016-08-01 14:04
I think this is normal behaviour, if i look at the documentation i see the following:

> tagging-tokens:
Specify keyboard keys that will trigger creation of a new tag. Multiple keys can be separated by a    pipe |, SPACE is declaration for literal spacebar. (Defaults to ENTER and ,)


Maybe you could change your code for the wanted behaviour you need?

**Comment by ps3331333** [comment] 2016-08-01 15:52
I believe the behavior of losing focus due to tabbing out or due to click should be the same (note in the PLUNK that if you first enter a value in ui-select, and then press tab to move to the next field, then you **don't** lose the value. 

I will be more than happy to change my code, but not sure what needs to be changed.

**Comment by Jefiozie** [comment] 2016-08-01 16:46
Hi @ps3331333 ,

Do you mean this behaviour?

[Link to demo plunker after focus](http://plnkr.co/edit/36IRP9J079vjWFIFjRSb?p=preview)

**Comment by ps3331333** [comment] 2016-08-01 23:17
Yes, first enter a value (don't select it) then click on the input field and the value will disappear.

**Comment by user378230** [comment] 2016-08-02 06:57
I can't search on mobile but there is already an issue/feature request for "tagging on blur". This is probably a duplicate of that. 

Will close when I can find it.

**Comment by Jefiozie** [comment] 2016-08-02 07:12
I think i found it check if it is the one you think it is. 

feat(tagging): enable tag-creation on blur #1732

**Comment by ps3331333** [comment] 2016-08-02 10:13
Yes, "on blur" applies to both tabbing out and clicking a different field.

**Comment by user378230** [comment] 2016-08-03 06:53
Closing as duplicate of existing blur requests.

**Closed by user378230** 2016-08-03 06:53 UTC
