### ISSUE TITLE
Clicking dropdown option doesn't select element

### ISSUE THREAD

**Issue by jordanthornquest** [angular-ui/ui-select#612] opened 2015-01-24 03:39 UTC
Hey, folks! I am running Angular 1.3.0, and I cannot seem to get the ui-select to function correctly when it comes to clicking on options. I copied the `demo.js` & the `bootstrap.html` demo files, and clicking on options does not add the options to a select, whether it is a single select or a multi-select.

**Comment by jordanthornquest** [comment] 2015-01-25 09:09
Hey, so here's some further diagnosis: this only happens when Batarang for AngularJS 0.7.4 is enabled. Seriously, it slows everything way, way down for ui-select, and makes it impossible to click on choices in order to select them.

**Comment by robshep** [comment] 2015-01-26 17:27
confirmed for me too.  Thanks for pointing out the chrome plugin workaround.  Strange!

**Comment by dparish** [comment] 2015-02-02 19:31
I'm seeing a similar problem but the examples work for me it's just my simple implementation that doesn't. I'm not sure batarang is the actual problem.

**Comment by uhomira** [comment] 2015-02-04 06:37
I had a similar problem that was solved by removing creepy Batarang.

**Comment by nickradford** [comment] 2015-02-06 04:10
That's bizarre about Batarang. Good find :smiley:

**Comment by toboid** [comment] 2015-02-13 10:51
Had the same problem, disabling Batarang fixed it. Thanks very much

**Comment by adamcmoore** [comment] 2015-02-28 17:38
Gah, I just spent an hour and half fighting this. Thank you Jordan!

**Comment by migajek** [comment] 2015-03-09 20:27
@jordanthornquest  THANK YOU. Just spent an hour trying to figure what is wrong. Batarang was disabled, had to enable & disable it.

**Comment by Dr4K4n** [comment] 2015-03-25 09:06
@jordanthornquest Thank you very much! Wasted at least an hour trying to find the cause. After disabling batarang everything works again -.- (Using Angular 1.3.15)

**Comment by mraible** [comment] 2015-03-26 18:10
@jordanthornquest Thanks for this solution. Ran into this today and fought it for a good hour. Using Angular 1.3.2 and disabling Batarang solved the problem. First google result - nice work!

**Comment by irizvi** [comment] 2015-05-27 18:29
+1 Thanks for the Batarang fix.

**Comment by xolraid** [comment] 2015-05-29 06:33
+1 Thanks for the Batarang fix.Thanks.

**Comment by wesleycho** [comment] 2016-03-27 20:18
Closing as a batarang issue (and duplicate of another closed issue).

**Closed by wesleycho** 2016-03-27 20:18 UTC
