### ISSUE TITLE
ui-select multiple height is 0 (zero) when disabled and has no items selected (bootstrap theme)

### ISSUE THREAD

**Issue by shkleinik** [angular-ui/ui-select#927] opened 2015-05-14 09:24 UTC
When I disable ui-select control in multiple mode and it has no items it collapses (is an issue for bootstrap theme)

```html
  <ui-select multiple ng-model="nothing" theme="bootstrap" ng-disabled="true">
    <ui-select-choices repeat="smth in smths>
    </ui-select-choices>
  </ui-select>
```

**Comment by MiguelMike** [comment] 2015-05-22 13:00
Seems to be not a theme specific issue.

**Comment by newbyca** [comment] 2015-05-26 07:08
I'm seeing this too. A fast workaround for me was to override:

**Comment by shkleinik** [comment] 2015-05-26 09:22
Workaround is good but fix is better :D

**Comment by newbyca** [comment] 2015-05-26 17:43
HA, I wish ...that's all I have time for at the moment. Some more info though: normally that css looks like:
```
.ui-select-multiple.ui-select-bootstrap {
    height: auto;
}
```
You probably noticed that the placeholder text also disappears when disabling the control. With height: auto, I think that's letting the height collapse. So a 'fix' might look like keeping the placeholder text around even when the control's disabled.

**Comment by icfantv** [comment] 2015-07-09 03:02
this is a duplicate of #379 and should be closed or merged.

**Comment by shahzadns** [comment] 2016-01-06 23:58
+1 for @newbyca's solution.  But still Placeholder doesn't shows up.

ui-select puts <code>ng-hide="$select.disabled"</code> on input field, which therefore adds <code>"ng-hide"</code> class.

So, in addition to above, I have to apply following style as well. Then, it looks perfect.
<code>
.ui-select-multiple .ui-select-search.ng-hide{
  width: 100%;
  display: inline-block !important;
  cursor: not-allowed;
}
</code>

Hope it helps other folks.
Cheers !

**Comment by wesleycho** [comment] 2016-03-27 22:13
Closing as a duplicate

**Closed by wesleycho** 2016-03-27 22:13 UTC
