### ISSUE TITLE
Dropdown does not open when clicked in Bootstrap theme 

### ISSUE THREAD

**Issue by wkwwong** [angular-ui/ui-select#165] opened 2014-08-22 05:26 UTC
This behaviour is different to that of the other two themes. There's a simple fix:

replace 
```html
ng-show=\"$select.items.length > 0\"
```
to
```html
ng-show=\"$select.open\"
```
in choices.tpl.html, 
```html
<ul class=\"ui-select-choices ui-select-choices-content dropdown-menu\" role=\"menu\" aria-labelledby=\"dLabel\" 
ng-show=\"$select.items.length > 0\">
...
</ul>
```

**Comment by dimirc** [comment] 2015-02-17 00:02
Closing since there isn't enough info to reproduce. Feel free to reopen if its persisting

**Closed by dimirc** 2015-02-17 00:02 UTC
