### ISSUE TITLE
<div ui-select-choices...> broken in angular v1.5.0

### ISSUE THREAD

**Issue by tangfang** [angular-ui/ui-select#1499] opened 2016-03-17 08:51 UTC
In the 1.5.0 version of angular
`<div ui-select-choices......></div>` is not supported.
must use `<ui-select-choices......></ui-select-choices>`

**Comment by user378230** [comment] 2016-03-17 11:15
Which version of ui-select are you using?

**Comment by tangfang** [comment] 2016-03-18 00:38
@user378230 0.15.0 version of ui-select

**Comment by tangfang** [comment] 2016-03-18 06:25
http://stackoverflow.com/questions/34805257/angular-compile-in-link-function-gives-an-error-rangeerror-maximum-call-stack#

**Comment by wesleycho** [comment] 2016-03-28 06:03
This sounds like it might be a duplicate of the double compile problem.

**Comment by user378230** [comment] 2016-04-30 13:50
Closing as resolved by #1555 as per https://github.com/angular-ui/ui-select/issues/1580#issuecomment-215276541

**Closed by user378230** 2016-04-30 13:50 UTC
Labels: needs: investigation, type: bug
