### ISSUE TITLE
hardwired "peopleObject" in uiSelectController.js

### ISSUE THREAD

**Issue by trilancer** [angular-ui/ui-select#1231] opened 2015-10-05 07:26 UTC
line:158
result.value = $scope.peopleObj[v];

A quick fix:
result.value = $scope[ctrl.parserResult.sourceName][v];

But obviously it doesn't support object hierarchy like config.US.states, which relates to how parserResult is generated.

**Comment by MiguelMike** [comment] 2015-10-12 08:38
Duplicate of #1217 which has been fixed in 0.13.1

**Closed** 2015-10-15 06:02 UTC
