### ISSUE TITLE
ng-disabled makes empty multiselect box looks strange

### ISSUE THREAD

**Issue by akcasoy** [angular-ui/ui-select#1432] opened 2016-02-14 13:35 UTC
Here is to see:
http://plnkr.co/edit/DkeH6CO4OWJKbW2Ie1UN?p=preview

Do not select anything from the list, just click on the disable button.

**Comment by user378230** [comment] 2016-02-15 16:47
Have a look at #379 (especially the last comment)

I think this essentially a duplicate of #1044 & #1156

**Comment by wesleycho** [comment] 2016-03-28 05:35
Closing as a duplicate.

**Closed by wesleycho** 2016-03-28 05:35 UTC
