### ISSUE TITLE
Web Page is Flickering

### ISSUE THREAD

**Issue by Vaasudevan** [angular-ui/ui-select#1317] opened 2015-11-23 13:00 UTC
While opening a drop down and now scroll down the web page and click some where around the document (say another drop down) ,now the scroll bar moves automatically to 1st dropdown then Click some where else in DOM don't focus to anyother drop down in the web page.

Refer this plunker  http://plnkr.co/edit/cCdXrV28xhqAagGEqvId?p=preview

**Comment by wesleycho** [comment] 2016-03-28 04:50
IMO this is the right behavior, as janky as this seems. The focus should absolutely return for accessibility reasons.

In addition, if you click another dropdown further down the page when another one is open, it seems to behave correctly with not going back to the first one.

Going to close this as expected behavior.

**Closed by wesleycho** 2016-03-28 04:50 UTC
