### ISSUE TITLE
Weird cursor on for Bootstrap theme on ie

### ISSUE THREAD

**Issue by SuTran** [angular-ui/ui-select#1643] opened 2016-06-07 06:46 UTC
### Bug description:

Step to produce:

1. Open the [example](http://angular-ui.github.io/ui-select/demo-basic.html) on Internet Explorer 
2. Type in Bootstrap example input
3. Click outside
4. Click on the text that was entered in step 2
5. Weird cursor happen

![image](https://cloud.githubusercontent.com/assets/4506521/15848091/e54aa8d6-2cb4-11e6-8c2a-7a864af63c33.png)

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.4.9
UI-Select: 0.17.1

**Comment by user378230** [comment] 2016-06-08 12:41
I don't think we can do much about "Weird cursors" might be more of a browser issue.

**Comment by SuTran** [comment] 2016-06-09 06:28
Hi @user378230 ,

Thank you for your reply. I don't think that related to browser issue. I tested [selectize.js](http://selectize.github.io/selectize.js/) (both selectize & bootstrap theme)on internet explorer also but I don't see any weird cursor there

### Version of Internet Explorer: 11

**Comment by user378230** [comment] 2016-09-28 16:17
Unable to reproduce on IE11, closing.

**Closed by user378230** 2016-09-28 16:17 UTC
