### ISSUE TITLE
angular1.4.9升级到1.5.0后，ui-select-choices不支持属性标注节点

### ISSUE THREAD

**Issue by tangfang** [angular-ui/ui-select#1498] opened 2016-03-17 08:40 UTC
`<div ui-select-choices repeat="project in (projects | filter: $select.search) track by project.uuid">
          <span ng-bind="project.name"></span>
        </div>`
以上的写法在angular1.4.9中可以正常运行，1.5.0中陷入compile死循环。
`<div ui-select-choices......` on angular1.4.9 yes.on angular1.5.0 no

**Comment by user378230** [comment] 2016-03-17 09:42
Closing as dupe of #1499

**Closed by user378230** 2016-03-17 09:42 UTC
