### ISSUE TITLE
ng-required does not set ui-select as $invalid in multi-select mode

### ISSUE THREAD

**Issue by jdmcnair** [angular-ui/ui-select#500] opened 2014-12-11 16:01 UTC
The `ui-select` element is still showing valid when no items are selected in multi-select mode and the ng-required directive is applied. It appears to invalidate correctly in single-select mode.

**Comment by abobwhite** [comment] 2015-01-27 21:49
+1 Looking for a workaround myself.

**Comment by wald-tq** [comment] 2015-02-18 18:44
+1 got the same issue. Have you found a solution yet?

**Comment by wald-tq** [comment] 2015-02-18 18:47
Duplicate of #258

**Closed** 2015-02-20 06:01 UTC
