### ISSUE TITLE
Opacity set to zero when no items binded

### ISSUE THREAD

**Issue by sercangurbuz** [angular-ui/ui-select#1652] opened 2016-06-13 12:21 UTC
updated to latest ui-select (Version: 0.17.1 - 2016-06-09T20:41:58.363Z), with angular 1.4.8.
ui-select-dropdown div opacity set to 0 when no items binded.

![image](https://cloud.githubusercontent.com/assets/5747927/16007231/e006ce9e-3179-11e6-87f1-7a23056a58b3.png)
[http://plnkr.co/edit/p0F5s5?p=preview](url)

**Comment by McGiogen** [comment] 2016-06-13 12:39
Same error here.
Ps: On bower the bugged version is registered as 0.18.0 but uiSelect changelog has only two 0.17.1, I think lastest one should be 0.18.0

**Comment by wescopeland** [comment] 2016-06-20 14:15
How in the world did this make it into production? I upgraded to 0.18.0 and literally every ui-select control in my application has regressed as a result of this problem.

**Comment by antch** [comment] 2016-06-27 14:42
Yeah, this is pretty serious, options never show up in any of my controls. Back to 0.17.1 I guess.

**Comment by evenicoulddoit** [comment] 2016-07-08 10:28
If you want to fix this in the mean (because it was quicker for me to do this than to revert to a known working version), you can add:

```css
.ui-select-dropdown.select2-drop-active {
    opacity: 1 !important;
}
```

**Comment by user378230** [comment] 2016-07-09 07:52
Could someone describe this problem here in more detail? If there are no items then there doesn't need to be a drop down? I assume I am missing something! :smiley:

@wescopeland whinging doesn't help solve issues, detailed bug reports and PRs do though! Consider helping out if via a PR if it's causing a big problem for you, will be happy to review :)

**Comment by evenicoulddoit** [comment] 2016-07-10 19:57
I'll try and make a short reproducible example tomorrow if I get the chance, but I also found this when I had only one result. The problem with the zero results case however is that the search is hidden, and I was serving the results up using API queries

**Comment by fynnfeldpausch** [comment] 2016-07-14 11:50
We had the same problem due to an active class name filter on the `$animateProvider`:

    function configureAnimateProvider($animateProvider) {
       $animateProvider.classNameFilter(/animate-/);
    }

This caused the callback at https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L1358 (which sets the opacity to 1) to not be executed (see https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L1405). After adding the ui-select classes to the filter, the callback is executed and the items appear:

    function configureAnimateProvider($animateProvider) {
       $animateProvider.classNameFilter(/animate-|ui-select-/);
    }

Maybe this helps someone with a similar issue...

**Comment by user378230** [comment] 2016-11-23 00:10
Closing this as the plunkr linked in the original post works against `v0.19.6` there is an issue with the classNameFilter as logged in #1731

**Closed by user378230** 2016-11-23 00:10 UTC

**Comment by alexander-elgin** [comment] 2017-02-18 04:04
@user378230 Please, you should revert this change. I load choices remotely based on the search value. If the search value is empty no choices are loaded. If no choices are available the dropdown (including the search field) is not shwn.
