### ISSUE TITLE
search-enabled="false" does not work with multiple select

### ISSUE THREAD

**Issue by wdrai** [angular-ui/ui-select#1034] opened 2015-06-21 16:38 UTC
http://plnkr.co/edit/rzJk5DYQ2ApHfveTeGCl?p=preview

The search input is still enabled (and search works) with the search-enabled="false" option

**Comment by thefewminutes** [comment] 2015-06-25 22:31
+1

**Comment by wdrai** [comment] 2015-07-01 08:45
Changing this in select.js works for me :
$templateCache.put("bootstrap/select-multiple.tpl.html", ... <input type=\"text\" **ng-readonly=\"!$select.searchEnabled\"** autocomplete=\"off\"...);

**Comment by user378230** [comment] 2016-03-16 14:08
This appears to be resolved in latest version (v0.16.0)

**Closed by user378230** 2016-03-16 14:08 UTC

**Comment by rafaeleyng** [comment] 2016-05-24 18:42
It doesn't work for me in v0.17.0, and it doesn't seem to work in the Plunker also.

**Comment by user378230** [comment] 2016-05-25 09:13
@rafaeleyng Which version? v0.17.1 is the latest. The plunkr I linked too works for me. 

Can you reproduce against one of the latest [Examples](http://angular-ui.github.io/ui-select/#examples)? (Please post plunkr too..)

**Comment by rafaeleyng** [comment] 2016-05-25 12:35
![image](https://cloud.githubusercontent.com/assets/4842605/15540020/e33bf54e-225b-11e6-8705-662fb5f52de1.png)

@user378230 The image above shows the Plunkr with version 0.17.0, `search-enabled="false"` for the select multiple and the search still works.

Am I doing something wrong?
