### ISSUE TITLE
directive not working on selectize 

### ISSUE THREAD

**Issue by MrOutput** [angular-ui/ui-select#1931] opened 2017-03-06 15:57 UTC
using latest selectize theme and latest angular.

### Bug description:
selecting items go to the last repeated element in the list. Occurs when `ui-select` is in an ng-repeat.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/FeMhrFYaPjvClL2TJbQQ?p=preview

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: latest

UI-Select: latest

Bootstrap/Select2/Selectize CSS (if applicable): Selectize latest css

 
![1488815097](https://cloud.githubusercontent.com/assets/8491687/23617215/f36a19e2-0251-11e7-9f01-0c2da8e5f2da.png)

![1488815189](https://cloud.githubusercontent.com/assets/8491687/23617222/fb79ada0-0251-11e7-8f17-8094510922b7.png)

**Comment by Jefiozie** [comment] 2017-03-07 07:36
Closing this one down as it is a duplicate of #1914

**Closed by Jefiozie** 2017-03-07 07:36 UTC
