### ISSUE TITLE
ui-select-no-choice isn't displayed

### ISSUE THREAD

**Issue by santosguilherme** [angular-ui/ui-select#1609] opened 2016-05-17 13:52 UTC
I have already downloaded the version 0.17.1, the directive "uiSelectNoChoice" is in file "dist/select.js", but when the search returns no results, it does not appear.

Doesn't work with ui-select add no-choice, [plunker link](http://plnkr.co/edit/T2HsEvQW1fBQJz3hg2dh?p=preview).

My code:
```
<ui-select ng-model="elementExtensions.ator" theme="bootstrap" fix-focus-ui-select>
    <ui-select-match allow-clear="true" placeholder="{{::'TYPE_FOR_SEARCH' | translate}}">
      {{$select.selected.name}}
    </ui-select-match>
    <ui-select-choices refresh="loadAsyncActors($select.search)" refresh-delay="300"
                       repeat="actor in actorPropertyViewControl.availableActors">
      <div ng-bind-html="actor.name | highlight: $select.search"></div>
    </ui-select-choices>
    <ui-select-no-choice>
      Dang! We couldn't find any choices...
    </ui-select-no-choice>
</ui-select>
```

HTML:
![selecao_014](https://cloud.githubusercontent.com/assets/8635147/15321554/a18ab2e2-1c0d-11e6-9ff8-86a05dc711ce.png)

**Comment by user378230** [comment] 2016-05-17 13:55
The `select.js`/`select.css` in your plunkr are outdated (`v0.16.1`) can you update to latest versions? (You can use the files from the `/dist/` here in the repo)

Thanks!

**Comment by santosguilherme** [comment] 2016-05-17 14:03
Updated.

**Comment by hut8** [comment] 2016-05-28 16:03
Seems like a duplicate of https://github.com/angular-ui/ui-select/issues/1608, no?

**Comment by santosguilherme** [comment] 2016-05-28 16:39
No, i'm using bootstrap theme.

**Comment by hut8** [comment] 2016-05-28 17:14
My mistake. Using 1.7.1 I am able to get it to display, but I can't figure out what's wrong with the plunkr at the moment.

**Comment by dimitarrusev** [comment] 2016-05-31 05:06
Strange. The directive is working fine with inline templates but not with external ones. Here’s a [plunk](https://plnkr.co/edit/mVwHRYHLKimfWyZ4zgAX?p=preview).

**Closed** 2016-05-31 11:48 UTC
Labels: type: bug
