### ISSUE TITLE
Search opens away from select when near viewport margins

### ISSUE THREAD

**Issue by kdsingharneja** [angular-ui/ui-select#1260] opened 2015-10-21 01:12 UTC
I have the ui-select in a div. There are about 50 items to search. If I open that div near the window bottom, then search appears to show selection on top of the select which seems correct, but when there are only 1-2 items as a search result, they are away from the select box.

Screenshot attached.
<img width="259" alt="screen shot 2015-10-20 at 9 08 14 pm" src="https://cloud.githubusercontent.com/assets/3587540/10625259/2fe2ac00-776f-11e5-9de8-fa0eac0496f9.png">

**Comment by fernandolvsouza** [comment] 2015-11-10 19:15
Hello, try this fix on file uiSelectDirective.js:

var setDropdownPosUp = function(offset, offsetDropdown){
          offset = offset || uisOffset(element);
          offsetDropdown = offsetDropdown || uisOffset(dropdown);

          dropdown[0].style.top = 'auto';
          dropdown[0].style.bottom = offset.height + 'px';

          //dropdown[0].style.position = 'absolute';
          //dropdown[0].style.top = (offsetDropdown.height * -1) + 'px';
          element.addClass(directionUpClassName);
};

**Comment by jchandra74** [comment] 2016-02-18 04:57
yeah experienced this as well +1

**Comment by wesleycho** [comment] 2016-03-28 03:32
Closing this as a duplicate of #1007.

**Closed by wesleycho** 2016-03-28 03:32 UTC
