### ISSUE TITLE
Project status/progress

### ISSUE THREAD

**Issue by starf** [angular-ui/ui-select#1351] opened 2015-12-10 08:20 UTC
I hate to be negative but there doesn't seem to be any progress here, can we agree that:
1) There are a massive amount of issues that need to be taken care of
2) ui-select is not a decent replacement for select2
?

Are we better off using another bootstrap-select project and doing things the native way? Or are there any other alternatives?

**Comment by simkessy** [comment] 2016-01-02 01:10
You find anything?

**Comment by faceleg** [comment] 2016-01-04 06:56
I'm using this module, @starf what do you find it lacks?

**Comment by sbokorna** [comment] 2016-01-18 14:27
There's no "order by".
Do you know how can I do it?

**Comment by sibeliusseraphini** [comment] 2016-01-19 19:13
who is maintaining this repo @dimirc ?

**Comment by user378230** [comment] 2016-03-15 23:18
Closing as dupe of #884

**Closed by user378230** 2016-03-15 23:18 UTC
