### ISSUE TITLE
keyboard is not opening on iPhone and iPad when you tap on the input

### ISSUE THREAD

**Issue by AndrewEastwood** [angular-ui/ui-select#1259] opened 2015-10-20 22:29 UTC

**Comment by wesleycho** [comment] 2016-03-28 03:28
Closing as a support issue.

**Closed by wesleycho** 2016-03-28 03:28 UTC

**Comment by ideadapt** [comment] 2016-03-30 07:06
Hi @wesleycho 
What does this mean, is it working now?

**Comment by AndrewEastwood** [comment] 2016-03-30 09:04
Interesting comment from @wesleycho.

**Comment by wesleycho** [comment] 2016-03-30 12:29
This is not a terribly useful issue without more details for a maintainer to look into without reproductions (preferably via Plunker) - feel free to open up an issue with those details.

I spent a lot of time this past weekend triaging issues in this repository since it needs a lot of love, but without minimum details, issues can be very costly to maintainers' mental overload to getting things fixed, or even if they are issues in many cases. With details & reliable reproductions, maintainers (or wouldbe contributors) have time saved from having to chase down if something is even an issue, and helps get things moving faster.

**Comment by AndrewEastwood** [comment] 2016-03-30 13:02
Minimum details is that you take an iphone and open a page where the ui-select is displayed and try to click on it and key some data. I'm sure you will see the issue with iOS native keyboard.
Using the Plunker cannot bring you that issue. You need to use native device.

**Comment by wesleycho** [comment] 2016-03-30 13:07
A Plunker would allow being able to see what happens. A device, or emulator such as the iOS Simulator can be used with it to debug any issues.

**Comment by AndrewEastwood** [comment] 2016-03-30 13:44
Plunker cannot emulate 100% device's functionality.

**Comment by wesleycho** [comment] 2016-03-30 13:47
Locking as unproductive conversation - Plunker **along with** iOS Simulator can improve the ability to debug something like this drastically.
