### ISSUE TITLE
on-select calls back too early.

### ISSUE THREAD

**Issue by antony** [angular-ui/ui-select#392] opened 2014-11-12 14:30 UTC
Hi,

I've noticed that if you pass the value of the select using on-select, it passes the PREVIOUS value.

If this is expected behaviour, it's undocumented. If it's unexpected, it's broken.

Plunkr here: http://plnkr.co/edit/OHpI2UlnILBK4qdtT1PI?p=preview

I noticed that waiting a short while shows the value updated. Looks like the on-selected trigger is just too early:

setTimeout(function() { console.log(selectionValue.selected); }, 1000);

**Comment by jnelson** [comment] 2015-07-07 21:04
NB: report plunker uses ui-select v0.8.2; relevant code has changed a lot since then.

**Comment by wesleycho** [comment] 2016-03-27 15:30
Closing due to age of issue - feel free to open a new issue with an up to date reproduction on Plunker using the latest release if this is still a problem.

**Closed by wesleycho** 2016-03-27 15:30 UTC
