### ISSUE TITLE
Is infinite scroll with remote data possible with ui-select?

### ISSUE THREAD

**Issue by BjoernKW** [angular-ui/ui-select#550] opened 2014-12-24 20:09 UTC
Is infinite scroll with remote data possible as described on http://ivaynberg.github.io/select2/ with ui-select?

For instance:

$("#e7").select2({
    placeholder: "Search for a repository",
    minimumInputLength: 3,
    ajax: {
        url: "https://api.github.com/search/repositories",
        dataType: 'json',
        quietMillis: 250,
        data: function (term, page) {
            return {
                q: term, //search term
                page: page // page number
            };
        },
        results: function (data, page) {
            var more = (page * 30) < data.total_count;
            return { results: data.items, more: more };
        }
    }
});

**Comment by PowerKiKi** [comment] 2015-01-27 09:22
Dupe of #221

**Closed by PowerKiKi** 2015-01-27 09:22 UTC

**Comment by amcdnl** [comment] 2015-04-06 15:37
Probably related to #620 too.
