### ISSUE TITLE
Bulk delete, plain delete (backspace) and left arrow will delete entire current search value

### ISSUE THREAD

**Issue by kkotosky** [angular-ui/ui-select#963] opened 2015-05-26 18:12 UTC
To reproduce:
1) Add in some search value on a select-multiple directive with search enabled.
    Highlight the first half of the search value including the first character. 
    Hit delete => entire search is deleted
2) Add in some search value on a select-multiple directive with search enabled.
    Continue hitting the left arrow until entire search value has been traversed. 
    Hit left arrow again => entire search is deleted
3) Add in some searh value on a select-multiple directive with search enabled.
    Move cursor to leftmost part of search value
    Hit backspace => entire search is deleted

I think In the first situation the second portion of the search value should remain so the user does not have to rewrite it when they only wanted to remove the first half. 
In the second and third situations I would think that the value should remain so the user can traverse and delete other tags and still have their search value remain so they can go back to it.

**Comment by wesleycho** [comment] 2016-03-27 22:28
Closing as a duplicate of #382.

**Closed by wesleycho** 2016-03-27 22:28 UTC
