### ISSUE TITLE
Unable to implement OptGroups when the actual options are down the tree

### ISSUE THREAD

**Issue by developer10** [angular-ui/ui-select#386] opened 2014-11-09 20:02 UTC
EDIT: Adding this StackOverflow question I just posted explaining in more detail what's wrong:
http://stackoverflow.com/questions/26832929/optgroups-with-ui-select-new-version-when-actual-options-are-below-what-should

I have an array of objects where one object contains the category name and then an object of items (id, name, etc.).

Array [
   {
        category: "This should be optgroup",
        options: [
        {
            id: 1,
            name: "Some name",
        },
        {
            id: 2,
            name: "Some name 2",
        },
        {
            id: 3,
            name: "Some name 3",
        }
        ]
   }
] 

Now my group-by function just does this to create all the optgroups:

return item.category;

And this part is fine. But since I need to be on the top of the complete array when in my repeater to be able to create optgroups this way, I'm having troubles with generating the actual options because if I add up to the string in my repeat="" then optgroups are obviously lost because the "item" has changed and category is no longer available from that spot.

Any advice?

**Comment by wesleycho** [comment] 2016-03-27 15:28
Closing due to age and confusing formatting - feel free to open a new issue if this is still a problem with more developer friendly formatting & reproduction of problem in Plunker based on the latest release.

**Closed by wesleycho** 2016-03-27 15:28 UTC
