### ISSUE TITLE
highlight and match no longer working for non-multiple tagging

### ISSUE THREAD

**Issue by bensurman** [angular-ui/ui-select#793] opened 2015-03-23 22:18 UTC
I haven't been able to pinpoint the exact reason yet but after updating from 0.10 to 0.11.2 the highlight and match functions are both broken for me on my existing code.  

From what I can see, the `searchInput.on('keyup')` event handler is now only in the multiple directive.  Might explain it, as most of the tagging handling is done there.

**Comment by seiyria** [comment] 2015-04-13 20:21
I'm also having this problem in my code, but for some reason it works in this plunkr: http://plnkr.co/edit/VGCKrSBaAL8KlSXihQgV?p=preview ... trying to figure out why has been pretty fruitless so far.

**Comment by wesleycho** [comment] 2016-03-27 21:02
Closing due to not enough actionable information - feel free to open a new issue with reproduction in Plunker based off of the latest release if it is still an issue.

**Closed by wesleycho** 2016-03-27 21:02 UTC
