### ISSUE TITLE
Select CSS not loading properly[Bug]

### ISSUE THREAD

**Issue by mukulgupta2507** [angular-ui/ui-select#1179] opened 2015-09-04 11:12 UTC
Hi,

I'm facing one issue related to css not being loaded properly with ui-bootstrap. I have opened an issue on SO: http://stackoverflow.com/questions/32396660/angular-ui-select-css-not-working-with-ui-bootstrap

It'll be great if someone can check if this is actually a bug or not .

Thanks

**Comment by mukulgupta2507** [comment] 2015-09-05 08:09
Found the issue. Select2.css was not loading which was creating the issue. Also, I found that ui-select is not compatible with select2#4.0.0. See this http://plnkr.co/edit/9RmB8aGddne6Ypy0dKBe?p=preview Please fix the plugin to be compatible with the latest version of Select2.

**Comment by TechFounder** [comment] 2015-12-04 22:32
I'm having the same issue. Specifically, using select2-rails gem 3.5.x along with ui-select 0.12.x. Upgrading both to the latest versions didn't seem to help.

**Comment by user378230** [comment] 2016-03-15 23:10
Closing as dupe of #986 

>I'm having the same issue. Specifically, using select2-rails gem 3.5.x along with ui-select 0.12.x. Upgrading both to the latest versions didn't seem to help.

Please open a new issue with a plunkr (or similar) against the latest version of ui-select (currently v0.16.0)

**Closed by user378230** 2016-03-15 23:10 UTC
