### ISSUE TITLE
Transclusion error in the link function of ui-select

### ISSUE THREAD

**Issue by DineshkumarT** [angular-ui/ui-select#227] opened 2014-09-26 13:44 UTC
link: function (scope, element, attrs, ctrl, transclude) {
          transclude(scope, function (clone) {
            element.append(clone);
          });
        }

transclude is throwing undefined error. 

Becasue of the above error,the dropdown is not showing any choices.

is there any alternative to fix it.

**Comment by askhogan** [comment] 2015-01-12 06:34
Getting this error on v1.2.8

**Comment by wesleycho** [comment] 2016-03-27 06:49
Closing due to age of issue - this may also be a duplicate.

Feel free to open a new issue with adequate reproduction on Plunker if this is still an issue.

**Closed by wesleycho** 2016-03-27 06:49 UTC
