### ISSUE TITLE
Render dropdown above the input if there is not room below

### ISSUE THREAD

**Issue by JoaoMosmann** [angular-ui/ui-select#719] opened 2015-03-04 20:14 UTC
Dropdown should be rendered above the input whether there're no space below it.

Example: 

Scroll down to the Select2
http://plnkr.co/edit/uvXvxEeuOHgvimHH6U6z?p=preview

It works in the Select2 examples https://select2.github.io/examples.html

**Comment by cmlenz** [comment] 2015-03-05 08:41
Duplicate of #148

**Comment by wesleycho** [comment] 2016-03-27 20:45
Closing as already addressed in the library by #1212

**Closed by wesleycho** 2016-03-27 20:45 UTC
