### ISSUE TITLE
How can I get access to input in form object

### ISSUE THREAD

**Issue by AndrewEastwood** [angular-ui/ui-select#1087] opened 2015-07-13 16:32 UTC
Just imagine that you have any select in a form and you wanna get any select through the form by select's name. How is it possible to do?

**Comment by wesleycho** [comment] 2016-03-27 23:21
Closing as duplicate of another issue - configuration to add input name support is a pre-existing feature request.

**Closed by wesleycho** 2016-03-27 23:21 UTC
