### ISSUE TITLE
ui-select-choices should allow object (hashtable) instead of array of objects

### ISSUE THREAD

**Issue by kutyel** [angular-ui/ui-select#1386] opened 2016-01-14 08:45 UTC
I have the following `ui-select` working:
```html
<ui-select ng-model="vm.example" name="example">
    <ui-select-match placeholder="Select...">{{$select.selected.key}}</ui-select-match>
        <ui-select-choices repeat="x in vm.examples | filter: $select.search">
            <div ng-bind-html="x.key | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>
```
And the source for this select is the following array...
```javascript
vm.examples = [
    {key:'a', value: 1},
    {key:'b', value: 2},
    {key:'c', value: 3}
]
```
However, I want my "datasource" for the select to be an object literal, as it follows...
```javascript
vm.examples = {
    a: 1,
    b: 2,
    c: 3
}
```
I have tried several times and couldn't be able to make it work, *is this even possible?* If it is not possible due to the `ui-select` current implementation... ***what is the reason??***

**Comment by user378230** [comment] 2016-01-27 22:07
Duplicate of #1255

**Comment by user378230** [comment] 2016-03-17 07:47
Closing due to lack of activity. Refer to https://github.com/angular-ui/ui-select/blob/161cff56c0ba9d4a86ae213056dd78ba18296036/examples/demo-object-as-source.html for examples of how to do this. (Or see wiki)

**Closed by user378230** 2016-03-17 07:47 UTC

**Comment by rodneicouto** [comment] 2016-07-06 14:49
I am adding the initial value. It is selected properly, but disappears from the list. Any idea?

**Comment by user378230** [comment] 2016-07-06 15:00
@rodneicouto #1672

**Comment by CaledoniaProject** [comment] 2016-09-12 08:09
demo is broken here
http://angular-ui.github.io/ui-select/demo-object-as-source.html

the dropdown lists are empty
