### ISSUE TITLE
Problem when the ng-model is initialized in a multiple select

### ISSUE THREAD

**Issue by Isaac6702** [angular-ui/ui-select#1435] opened 2016-02-15 22:42 UTC
Hi,

if I have initialized the ng-model places but get doubled in the list that can be?

    <ui-select multiple ng-model="user.sportsPreferences" theme="bootstrap" ng-disabled="disabled" title="Choose a sports preferences" >
        <ui-select-match >{{$item.name}}</ui-select-match>
        <ui-select-choices repeat="sportsPreference in sportsPreferences | filter:{id: $select.search} track by sportsPreference.id">
            {{sportsPreference.name}}
        </ui-select-choices>
    </ui-select>

**Comment by wesleycho** [comment] 2016-03-28 05:36
Can you post a reproduction in Plunker?

**Comment by user378230** [comment] 2016-07-10 21:08
Closing due to lack of update & no plunkr.

**Closed by user378230** 2016-07-10 21:08 UTC
Labels: needs: plunkr
