### ISSUE TITLE
On IE, Beforeunload event is triggered when user picks an option from the dropdown list

### ISSUE THREAD

**Issue by harry-kalligeros** [angular-ui/ui-select#203] opened 2014-09-19 06:46 UTC
On Internet Explorer 10, Beforeunload event is triggered when user picks an option from the dropdown list.
I tested with ui-select 0.6.0, 0.7.0.
I guess beforeunload event is triggered because browser detects changes in the DOM. Other browsers do not present this problem. I use beforeunload on the window object in order to prompt user if he wants to leave page, but this behaviour of ui-select is annoying. 

Plunker: http://embed.plnkr.co/sQjbat/preview

**Comment by elutz** [comment] 2015-03-16 13:05
I made a pull request containing the above by @harry-kalligeros mentioned changes, see #762

**Comment by clintam** [comment] 2015-11-25 21:55
I think this could be closed. Issue appears fixed by fb88ec8

**Comment by clintam** [comment] 2015-11-26 17:29
I have confirmed the issue is fixed in IE10. Thats great news!

Can anyone provide a timeline of when that fix (https://github.com/angular-ui/ui-select/commit/fb88ec845355ad0c239a6bec3c284ad988d4af60) would make it into a released version? We are anxious to consume it.

Thanks,

**Comment by wesleycho** [comment] 2016-03-27 06:36
Closing as fixed.

**Closed by wesleycho** 2016-03-27 06:36 UTC
