### ISSUE TITLE
Cannot select initial value in case search-enabled="false"

### ISSUE THREAD

**Issue by peterreisz** [angular-ui/ui-select#1653] opened 2016-06-13 13:09 UTC
Create a simple ui-select with search-enabled="false" option and set an initial value via ng-model.
Open the ui-select: the initial value is selected, but not shown in the list.
If I select another value, I cannot select the initial value again.
It works fine in case there is no initial value.
The previous version (0.17.1) also works fine.

Plunkr: http://plnkr.co/edit/s9NbZwbonSCLAIF3JK39?p=preview

Angular.js: v1.5.6
Bootstrap: v3.3.6
Ui-select: v0.18.0

**Comment by peterreisz** [comment] 2016-06-13 14:42
I've just found the [removeSelected ](https://github.com/angular-ui/ui-select/wiki/ui-select#examples-disabling-instead-of-removing-selected-items-in-multiple-selection) feature introduced in the version 0.18.0.
I think this should only affect the multiselect version. Turning it off solves the problem.

**Comment by gilluminate** [comment] 2016-06-13 23:00
Having the same issue. +1

**Comment by kaareloun** [comment] 2016-06-23 07:06
+1

**Comment by Jefiozie** [comment] 2016-06-30 06:03
Is this not a duplicate of #1672?

**Comment by gilluminate** [comment] 2016-06-30 16:22
well, since this thread started 17 days ago, and that one started 10 days ago. I'd wager that it is a duplicate of this. 😆

**Comment by Jefiozie** [comment] 2016-06-30 18:06
Sorry for that..but the  good thing is that there 's a fix now just wait for a release.

**Comment by user378230** [comment] 2016-07-10 21:16
Should be resolved as of `v0.18.1` see PR linked in #1672

**Closed by user378230** 2016-07-10 21:16 UTC
