### ISSUE TITLE
Provide option to add no-value choice

### ISSUE THREAD

**Issue by just-boris** [angular-ui/ui-select#302] opened 2014-10-14 10:52 UTC
Angular.js [select directive](https://docs.angularjs.org/api/ng/directive/select) have a convenient way to define null-value option. If you put `<option>` tag without value inside `<select>`, it will be treated as null-option which sets model value to `null`.
It is useful sometimes to provide user ability to reset selected value. Now I have to implicitly add that item to other choices in repeat.

```js
$scope.persons = [{"id": null, "name": "No person"}].concat(otherPersons)
```
```html
<ui-select ng-model="form.person">
    <ui-select-match placeholder="Select person...">{{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="person.id as person in persons">{{person.title}}</ui-select-choices>
</ui-select>
```
I don't want to do it and it would be good if you will have an option for provide this option through html, for example
```html
<ui-select ng-model="form.person">
    <ui-select-match placeholder="Select person...">{{$select.selected.name}}</ui-select-match>
    <ui-select-null-choice>No person</ui-select-null-choice>
    <ui-select-choices repeat="person.id as person in persons">{{person.title}}</ui-select-choices>
</ui-select>
```
It is similar to select directive logic and looks good for me. What do you think?

**Comment by jasny** [comment] 2015-01-16 10:08
+1

**Comment by fantasia949** [comment] 2015-01-26 07:03
+1

**Comment by Anton-Nikishkin** [comment] 2015-01-26 13:47
+1

**Comment by akirich** [comment] 2015-01-27 21:48
+1

**Comment by veob** [comment] 2015-02-06 12:25
+1

**Comment by kunashir** [comment] 2015-02-12 12:27
+1

**Comment by Blarm1959** [comment] 2015-02-18 00:53
+1

**Comment by dlukez** [comment] 2015-02-25 05:11
Guys, check this out and tell me if it suits your needs... http://plnkr.co/edit/7nmBRicsmH33E55sSomz

**Comment by Reklino** [comment] 2015-02-25 22:39
That solution looks great to me. In my opinion, it would be best if the null option is not filterable. That way there is always a way to set the box back to null.

**Comment by akirich** [comment] 2015-02-25 22:48
absolutely you are right
null option should be always selectable

**Comment by dlukez** [comment] 2015-02-25 22:54
That's how I had it working in the first place but the requirement for my project dictated that the option should be filterable...

**Comment by dlukez** [comment] 2015-02-25 22:58
Just checked ngOptions -> it's not filterable. Maybe we mimic that behaviour?

**Comment by Reklino** [comment] 2015-02-25 23:00
Maybe there should be an option for the null option to filterable or not? Something like 'null-filterable="true"'. That may be a bit much though...

**Comment by dlukez** [comment] 2015-02-25 23:40
The problem there is that the developer is performing the filtering, so there's no way to hook in to their implementation and I would be adverse to changing the source array through the use of these attributes. We can always reset back to null by clearing the search term to re-show the null option? Or we may want to hook in to the ui-select-match allow-clear functionality also?

**Comment by akirich** [comment] 2015-02-26 00:35
yes, adding clear button support (and displaying placeholder text for NULL
values) would solve this issue as well

just to be clear - we now have several implementations in our current
project - see 3 drop downs on the screenshot below

1) regular ui-select
the most basic one

2) hierarchical ui-select
this is ui-select with few modifications:
a) http://codepen.io/chrishanson/pen/nqcGA
b) clear button added (similar to react-select)

3) react-select
it has clear value button out of the box

[image: Inline images 1]


based on this experience using all kinds of different drop-downs - we liked
clear button & null-value handling (with placeholder text displayed)

**Comment by FFelling** [comment] 2015-02-26 09:36
I also would like the null-option the always be selectable.
What i do not like is that the null-option is part of the data array. I would like to see that nullability could be enabled/disabled and that you can specifiy at least the text to display for the nullable item ("Please select XYZ").

**Comment by dlukez** [comment] 2015-02-26 22:57
@akirich so are you saying that you believe the null option and the clear button should do the same thing?

@FFelling As it stands, the code I've written isn't really adding a lot of support for null option stuff considering that the user still has to specify it in their collection. Perhaps I'll modify the functionality so that:

1) If the null option doesn't exist in the original collection, it will be added to the dropdown without modifying the original collection. In this case, the option **won't** be filterable.

2) If the null option does exist in the original collection... Well, we just leave it, but transform the model value to null instead of the null option descriptor. The developer can then implement filtering however they like.

As far as displaying the null option is concerned (i.e. "Please select XYZ"), I am leaning towards reusing the template provided inside the choices element to provide the most flexibility. I've had templates that are quite complex and would require control over how the null option is displayed (it wouldn't just be a string). In this case, if the items in the original collection were just strings I could write `null-option="Please select XYZ"`, however if they were objects of the form `{ id: 1, name: "Item" }` and the template was `{{ item.name }}`, I would need to specify `null-option="{ name: 'Please Select XYZ' }"`.

I am not clear yet on the best relationship between the clear button and the null option... Any thoughts?

**Comment by akirich** [comment] 2015-02-26 23:16
yes. I believe clear button (which would set value to null) and placeholder
text for null value would solve this better than adding null-value option
into options list (and dealing with filterable / not filterable null-value
option)

**Comment by dlukez** [comment] 2015-02-26 23:19
@akirich isn't this what `allow-clear` on `ui-select-match` does?

**Comment by akirich** [comment] 2015-02-26 23:42
yes ! it didn't work for me as I've found we already have modified
template...
checked on the demo page - it works, this is exactly what I've had in mind !

**Comment by FFelling** [comment] 2015-02-27 08:51
This issue has some history. Some time ago there was no generic way to clear ui-select when using the bootstrap template. There was no clear button and no null option. The only option was to add a null-item to the data collection prior to binding.

The clear button has since been added and works as expected.

We still would like to have a null option that is not part of the original data collection. When it is specified and you press the clear button the null option should be selected when present.

I like @dlukez proposed solution  (null-option="{ name: 'Please Select XYZ' }") for it's flexibility.

**Comment by pgrm** [comment] 2015-03-06 12:40
I'm currently using the placeholder to specify the description of the null option, but it is a bit weird, would really like to have an explicit null-option

**Comment by idoo** [comment] 2015-03-09 09:51
+1

**Comment by kr4ng** [comment] 2015-03-18 18:31
I am trying to figure out how to use ui-select to emulate google style search (i.e., where the user can search any string they want or select something from the menu in the dropdown). Is this possible? right now, I can only get onselect function to trigger when i select an item from the menu and not when they just type in a random string that doesn't match anything.

**Comment by stevematyas** [comment] 2015-07-06 20:19
Will the null-option support be included for a multiple select?

**Comment by nullpunkt** [comment] 2015-08-13 07:24
+1

**Comment by burzum** [comment] 2015-09-03 14:22
+1

**Comment by reyx** [comment] 2015-09-07 03:44
+1

**Comment by landasystems** [comment] 2015-09-09 16:16
+1

**Comment by jraguilo** [comment] 2015-09-17 18:47
My problem with the allow clear button is that if I were to use only keyboard, I would have no way to clear the value in my dropdown, but if we had a null option, then I could simply delete my search text and choose my null option.

**Comment by jtrancas** [comment] 2015-11-03 02:41
+1

**Comment by nadavsinai** [comment] 2015-11-03 11:45
+1

**Comment by soichih** [comment] 2015-11-10 02:55
+1

**Comment by jitendersandhu** [comment] 2015-11-25 08:15
+1

**Comment by jefersondaniel** [comment] 2015-11-26 18:48
+1

**Comment by PavelKonon** [comment] 2015-11-30 11:26
+1

**Comment by LeleDev** [comment] 2015-12-02 15:35
+1

**Comment by just-boris** [comment] 2015-12-21 11:54
Hello, folks. I tried to implement this feature, but it is more complicated that it seemed initially.

ui-select has very difficult transclusion logic, so I can't insert one more nested directive and inject it into dropdown.

Also I found a fix in related project: https://github.com/RenovoSolutions/TypeScript-Angular-Components/pull/91. Here it was done via extra configutation option for main directive itself. Maybe we here should do the same.

**Comment by jibusayone** [comment] 2016-01-21 12:52
Is this allow-clear option a newly added one ? For me, adding allow-clear="true" doesn't make any effect. I am using ui-select theme select2 3.5.1.

**Comment by just-boris** [comment] 2016-01-21 13:00
@jibusayone `allow-clear` option should be added to `<ui-select-match>` element, not `<ui-select>`.

**Comment by jibusayone** [comment] 2016-01-22 05:46
<addr> test

**Comment by jibusayone** [comment] 2016-01-22 05:47
```
test
```

**Comment by jibusayone** [comment] 2016-01-22 05:51
@just-boris I did the same, but didn't work. This is the html snippet.
```
<ui-select ng-model="vendor.country" name="country" theme="select2" class="input-sm country">
    <ui-select-match allow-clear="true" placeholder="Select country...">{{ $select.selected.name }}</ui-select-match>
        <ui-select-choices repeat="country.id as country in countryCollection|filter:$select.search">{{ country.name }}</ui-select-choices>
</ui-select>
```

**Comment by jibusayone** [comment] 2016-01-22 09:09
I just found out the issue. It was the version which was causing the problem. 
But I don't want to upgrade to the latest 0.13.2 where my current design gets affeected. Does anyone know in which update the allow-clear feature was included?

**Comment by wesleycho** [comment] 2016-03-27 07:03
Closing as a duplicate of #152 - this issue has too many +1s which has made this a noisy issue to read, and #152 proposes a nice solution to this problem.

**Closed by wesleycho** 2016-03-27 07:03 UTC

**Comment by MyEidos** [comment] 2016-10-13 09:02
Could someone clarify, this thing is not ready yet? I need the same thing that in OP post, a way to add "-- please select--" option to dropdowns.
