### ISSUE TITLE
ng-repeat of objects uses $$hashkey, but i declare 'track by'

### ISSUE THREAD

**Issue by estvmachine** [angular-ui/ui-select#1050] opened 2015-06-30 17:43 UTC
Hi, i got a problem, i declare the ng-repeat of lists of objects using track by uniqueid, but the ui-select still uses '$$hashkey' like he cant reconognize the track.

```html
<ui-select
                               multiple
                               ng-init= "typeDocumentsAll= listTypeDocs()"
                               ng-model="searchParams.typedocs"
                               theme="select2"
                               style="width: 200px;">
                      <ui-select-match placeholder="Select the type of document.">
                                {{$item.code}}
                      </ui-select-match>
                      <ui-select-choices
                            repeat="typedoc in (typeDocumentsAll | filter:$select.search) 
                                                                                  track by typedoc.code "
                      >
                        <div ng-bind="typedoc.code"></div>
                        <small>
                          name: <span ng-bind-html="''+typedoc.name | highlight: $select.search"></span>
                        </small>
                      </ui-select-choices>
                    </ui-select>
```

This is relationed to #665

**Comment by user378230** [comment] 2016-03-17 07:51
I think this is a dupe of #665 so closing.

**Closed by user378230** 2016-03-17 07:51 UTC
