### ISSUE TITLE
Question: template when search returns no results

### ISSUE THREAD

**Issue by paulflo150** [angular-ui/ui-select#615] opened 2015-01-25 17:09 UTC
First of all thanks for this wonderful plugin.

Is there a way to display a custom template when the search returns no results? What I would like to do is provide a basic template with some text and a button which will allow me to trigger an action (i.e.: Add a new item).

Secondly, I am limiting the number of items displayed, so I would like to be able to inform the user that only 50 items out of 200 for instance are being shown.

I can't figure out how to do this without modifying the directives.

Any help is appreciated, thanks.

**Comment by ravishivt** [comment] 2015-02-03 00:44
+1

**Comment by awerlang** [comment] 2015-03-14 01:38
If search returns some results, but none of what user is looking for, shouldn't she be able to add a new item?

Someway related to #697

**Comment by user378230** [comment] 2016-03-16 16:28
Dupe of No result template #831 

You can also modify the *theme*/choices.tpl.html as necessary.

**Closed by user378230** 2016-03-16 16:28 UTC
