### ISSUE TITLE
async data refresh and multi-select

### ISSUE THREAD

**Issue by Ir1sh** [angular-ui/ui-select#962] opened 2015-05-26 17:44 UTC
When using the multi-select directive when the choices refreshes the dropdown list does not seem to be aware of the already selected choices.  This means that if an already selected option is returned from the async call it is displayed in the dropdown list and if you select it you get an ng-repeat dupes error

Here is my html

```
<div ui-select-choices
  repeat="person in people | GuestListFilter: $select.search track by person.trackBy"
  refresh="getUserSuggestions($select.search)">
</div>
```

and relevant js

```
					$scope.people = [];
					$scope.getUserSuggestions = function(q) {
						FormService.getUsers(q).then(function(response) {
							$scope.people = _.map(response, function(suggestion) {
								return {
									bh: true,
									trackBy: buildTrackBy(suggestion.id, suggestion.userName),
									user: suggestion
								};
							});
						});
					};
```

**Comment by Diaoul** [comment] 2015-05-27 17:47
I have the same issue using Restangular to populate my $scope.

**Comment by mpetrovic** [comment] 2015-06-10 20:30
I'm having this issue as well. 

I populate the list of all items through an ajax call. Then I populate the list of selected items using the same objects, to make sure that it's not stupid javascript object equality.

I've spent the past couple days digging. uiSelectCtrl.refreshItems() gets the list of selected items from uiSelectCtrl.selected. The only place I can see this being set is in [ngModel.$render](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectMultipleDirective.js#L143). The issue is that once this is set after an asynchronous action, uiSelectCtrl.refreshItems() isn't run again. 

Should it be?

**Comment by ojosdegris** [comment] 2015-06-25 13:03
So how you work around it ? Do you just modify your `GuestListFilter` to hide already selected options?

**Comment by countrogue** [comment] 2015-07-28 15:13
I called uiSelectCtrl.refreshItems(); from the refresh function and it worked for me. 
```javascript
<ui-select-choices repeat="exp.name as exp in expertise | filter:{name:$select.search}"
                   refresh="refreshExpertise($select.search, $select)"
                   refresh-delay="100">
    {{exp.display}}
</ui-select-choices>
```

```javascript
$scope.refreshExpertise = function(search,select) {
    select.refreshItems();
};
```

**Comment by ojosdegris** [comment] 2015-07-28 17:40
@countrogue I end up with exactly the same solution. thanks!

**Comment by sars** [comment] 2015-08-06 16:47
It didn't work for me, I solved it replacing choices that already exist in selected with objects from selected.

```
        $scope.choices = fromBackend.map(function (i) {
          return _.find(select.selected, {value: i.id}) || {label: i.name, value: i.id};
        });
```

**Comment by JonathanTech** [comment] 2016-03-10 01:24
I don't have time to do a full PR with testing, or even to clean it up, but this is how I've solved it. I replaced this section of code https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L484-L487
```javascript
if ( data !== undefined ) {
          var filteredItems = data.filter(function(i) {return selectedItems && selectedItems.indexOf(i) < 0;});
          ctrl.setItemsFn(filteredItems);
        }
```

with this:
```javascript
       if ( data !== undefined ) {
          var checkByTrackBy = function(item, selectedItems){
            var propsItemNameMatches = /(\w*)\./.exec(ctrl.parserResult.trackByExp);
            var matches = /\.([^\s]+)/.exec(ctrl.parserResult.trackByExp);
            if(propsItemNameMatches && propsItemNameMatches.length > 0 && propsItemNameMatches[1] == ctrl.parserResult.itemName){
              if(matches && matches.length>0) {
                for(var i = 0; i < selectedItems.length;i++){
                  var selectedItem  = selectedItems[i]
                  if(item[matches[1]] == selectedItem[matches[1]]){
                    return false;
                  }
                }
                return true
              }
            }
          }
          var filteredItems = data.filter(function(i) { return selectedItems && (ctrl.parserResult.trackByExp) ? checkByTrackBy(i,selectedItems) : selectedItems.indexOf(i) < 0 ;});
          ctrl.setItemsFn(filteredItems);
        }
```

**Comment by wesleycho** [comment] 2016-03-27 22:24
Closing as a duplicate issue.

**Closed by wesleycho** 2016-03-27 22:24 UTC
