### ISSUE TITLE
Allow individual choices (ui-select-choice directive)

### ISSUE THREAD

**Issue by justinwinslow** [angular-ui/ui-select#1331] opened 2015-11-29 00:50 UTC
I might just be missing something but it doesn't seem like there's a way to just write the available options into the view like a normal select box. If that's the case it would be great if there was a singular choice directive:

```html
<ui-select ng-model="model">
  <ui-select-match placeholder="Some text"></ui-select-match>
  <ui-select-choice ui-select-value="Some Value">
    Some Label
  </ui-select-choice>
  <ui-select-choice ui-select-value="Another Value">
    Another Label
  </ui-select-choice>
</ui-select>
```

**Comment by user378230** [comment] 2016-03-15 22:56
Closing as dupe of #152

**Closed by user378230** 2016-03-15 22:56 UTC
