### ISSUE TITLE
100% CPU when using ui-select-choices attribute form

### ISSUE THREAD

**Issue by glutentag** [angular-ui/ui-select#1580] opened 2016-04-27 05:48 UTC
When using ui-select-choices in its attribute form
`<div data-ui-select-choices ...></div>` its freezes the browser with 100% CPU.

To reproduce it, just change `<ui-select-choices` to `<div data-ui-select-choices ...></div>` in any plunker demo.

Angular: 1.5.5
UI-Select: 0.16.1

**Comment by user378230** [comment] 2016-04-27 12:13
Duplicate of #1499 

This was actually resolved by #1555 I think, but the plunkr's are using an outdated select.js because they were built from a branch that was behind master (#1578) when I merge the next PR it should fix itself. The fix in #1555 isn't currently released. We'll hope to get it out soon.

If you need a working dist/select.js you can use https://github.com/angular-ui/ui-select/blob/bc35d050a79ebab99916dcba6f6ad99d03fa264b/dist/select.js while waiting for the plunkrs to be updated and a new version released.

**Closed by user378230** 2016-04-27 12:13 UTC

**Comment by glutentag** [comment] 2016-04-28 00:56
Thank you for the quick answer, it fixes indeed my issue. Sorry I missed the duplicate.
